#!/usr/bin/env bash
# ============================================================================
# DailyLedger — Deploy Patch #5: FIX duplicate Loans/Borrowing content
#   (caused by patch_4 being re-run after the GitHub auth failure)
#
# ROOT CAUSE: patch_4's "already applied?" check tested whether the OLD
# anchor text was gone. But those edits were written as new = old + extra
# (appending content after an anchor), so the OLD text stayed present even
# after applying — the check never triggered, and the retry re-appended
# everything a second time. This produced:
#   - A duplicate "Loans / Borrowing" tab button
#   - A duplicate <div id="tab-loans"> panel
#   - A duplicate "loansDetailChart" canvas + a duplicate `new Chart(...)` call
#   - `const loanLabels` declared TWICE in the same <script> block — this is
#     a JavaScript SyntaxError, which silently killed the ENTIRE script on
#     that page: not just the Loans tab, but every tab and every chart
#     (Expense/Income/Payment/Savings included) stopped working.
#   - The same block of Python duplicated (harmless but wasteful) in views.py
#
# THIS SCRIPT: removes exactly the duplicated content, restoring each
# element to exactly one copy. Verified beforehand against an exact replica
# of the current (bugged) production files — before/after byte counts and a
# full functional re-test (correct totals, zero duplicate markers, page
# loads 200) all confirmed clean.
#
# Also fixes the underlying flaw: this script's own idempotency check tests
# for the OLD (broken, duplicated) text specifically — so it is safe to
# re-run, and unlike patch_4, a retry here cannot re-duplicate anything,
# because the fix is a pure removal, not an append.
#
# USAGE: paste this whole block directly into your SSH session.
# ============================================================================
set -euo pipefail

PROJECT_DIR="$HOME/dailyledger"
cd "$PROJECT_DIR"

echo "== 0. Pre-flight =="
if [ -d "venv" ]; then source venv/bin/activate; echo "Activated venv/"
elif [ -d ".venv" ]; then source .venv/bin/activate; echo "Activated .venv/"
else echo "WARNING: no venv/ found — using system python3."; fi

echo
echo "== 1. MANDATORY BACKUP (before touching anything) =="
DB_BACKUP_DIR="$PROJECT_DIR/backups/database"
PROJECT_BACKUP_DIR="$PROJECT_DIR/backups/project"

python manage.py run_backup --skip-notify

AFTER_DB_FILE=$(find "$DB_BACKUP_DIR" -name '*.sql.gz' -newermt '-2 minutes' 2>/dev/null | sort | tail -1)
AFTER_PROJ_FILE=$(find "$PROJECT_BACKUP_DIR" -name '*.tar.gz' -newermt '-2 minutes' 2>/dev/null | sort | tail -1)

if [ -z "$AFTER_DB_FILE" ] || [ ! -s "$AFTER_DB_FILE" ]; then
    echo "!! ABORT: no fresh, non-empty database backup file found — cannot verify backup succeeded."
    exit 1
fi
if [ -z "$AFTER_PROJ_FILE" ] || [ ! -s "$AFTER_PROJ_FILE" ]; then
    echo "!! ABORT: no fresh, non-empty project archive backup file found — cannot verify backup succeeded."
    exit 1
fi
echo "Backup verified:"
echo "  DB:      $AFTER_DB_FILE ($(du -h "$AFTER_DB_FILE" | cut -f1))"
echo "  Project: $AFTER_PROJ_FILE ($(du -h "$AFTER_PROJ_FILE" | cut -f1))"
echo "Safe to proceed."

echo
echo "== 2. Confirming the duplication is actually present (sanity check) =="
BTN_COUNT=$(grep -c 'id="tab-btn-loans"' templates/ledger/detail_reports.html || true)
PANEL_COUNT=$(grep -c 'id="tab-loans"' templates/ledger/detail_reports.html || true)
CHART_COUNT=$(grep -c "const loanLabels" templates/ledger/detail_reports.html || true)
echo "  tab-btn-loans occurrences: $BTN_COUNT (2 = bug present, 1 = already fixed)"
echo "  tab-loans occurrences: $PANEL_COUNT"
echo "  const loanLabels occurrences: $CHART_COUNT"
if [ "$BTN_COUNT" -le 1 ] && [ "$PANEL_COUNT" -le 1 ] && [ "$CHART_COUNT" -le 1 ]; then
    echo "  Nothing duplicated — already clean. Skipping straight to verification below."
    SKIP_PATCH=1
else
    SKIP_PATCH=0
fi

echo
echo "== 3. Git status before patch =="
git status --short

if [ "$SKIP_PATCH" -eq 0 ]; then
echo
echo "== 4. Removing the duplicated content =="
python3 - <<'PYEOF'
import base64, json, sys

MANIFEST_B64 = """
eyJlZGl0cyI6IFt7InBhdGgiOiAibGVkZ2VyL3ZpZXdzLnB5IiwgIm9sZCI6ICJcbiAgICBsb2Fuc190YWtlbl9xcyA9IExvYW4ub2JqZWN0cy5maWx0ZXIodGVuYW50PXRlbmFudCwgZGF0ZV9fZ3RlPXN0YXJ0X2RhdGUsIGRhdGVfX2x0ZT1lbmRfZGF0ZSlcbiAgICBsb2FuX3JlcGF5bWVudHNfcXMgPSBMb2FuUmVwYXltZW50Lm9iamVjdHMuZmlsdGVyKHRlbmFudD10ZW5hbnQsIGRhdGVfX2d0ZT1zdGFydF9kYXRlLCBkYXRlX19sdGU9ZW5kX2RhdGUpXG4gICAgbG9hbl9tYXAgPSB7fVxuICAgIGZvciByb3cgaW4gbG9hbnNfdGFrZW5fcXMudmFsdWVzKCdzb3VyY2UnKS5hbm5vdGF0ZSh0b3RhbD1TdW0oJ2Ftb3VudCcpLCBjb3VudD1Db3VudCgnaWQnKSk6XG4gICAgICAgIGVudHJ5ID0gbG9hbl9tYXAuc2V0ZGVmYXVsdChyb3dbJ3NvdXJjZSddLCB7J3Rha2VuJzogRGVjaW1hbCgnMCcpLCAncmVwYWlkJzogRGVjaW1hbCgnMCcpLCAnY291bnQnOiAwfSlcbiAgICAgICAgZW50cnlbJ3Rha2VuJ10gPSByb3dbJ3RvdGFsJ11cbiAgICAgICAgZW50cnlbJ2NvdW50J10gKz0gcm93Wydjb3VudCddXG4gICAgZm9yIHJvdyBpbiBsb2FuX3JlcGF5bWVudHNfcXMudmFsdWVzKCdsb2FuX19zb3VyY2UnKS5hbm5vdGF0ZSh0b3RhbD1TdW0oJ2Ftb3VudCcpLCBjb3VudD1Db3VudCgnaWQnKSk6XG4gICAgICAgIGVudHJ5ID0gbG9hbl9tYXAuc2V0ZGVmYXVsdChyb3dbJ2xvYW5fX3NvdXJjZSddLCB7J3Rha2VuJzogRGVjaW1hbCgnMCcpLCAncmVwYWlkJzogRGVjaW1hbCgnMCcpLCAnY291bnQnOiAwfSlcbiAgICAgICAgZW50cnlbJ3JlcGFpZCddID0gcm93Wyd0b3RhbCddXG4gICAgICAgIGVudHJ5Wydjb3VudCddICs9IHJvd1snY291bnQnXVxuICAgIGxvYW5fbmFtZXMgPSBzb3J0ZWQobG9hbl9tYXAua2V5cygpKVxuICAgIGxvYW5fYnJlYWtkb3duID0gW3snbmFtZSc6IG4sICduZXQnOiBsb2FuX21hcFtuXVsndGFrZW4nXSAtIGxvYW5fbWFwW25dWydyZXBhaWQnXSwgKipsb2FuX21hcFtuXX0gZm9yIG4gaW4gbG9hbl9uYW1lc11cbiAgICB0b3RhbF9wZXJpb2RfbG9hbnNfdGFrZW4gPSBzdW0oKHJvd1sndGFrZW4nXSBmb3Igcm93IGluIGxvYW5fYnJlYWtkb3duKSwgRGVjaW1hbCgnMCcpKVxuICAgIHRvdGFsX3BlcmlvZF9sb2Fuc19yZXBhaWQgPSBzdW0oKHJvd1sncmVwYWlkJ10gZm9yIHJvdyBpbiBsb2FuX2JyZWFrZG93biksIERlY2ltYWwoJzAnKSlcbiAgICBjdXJyZW50X2xvYW5zX291dHN0YW5kaW5nID0gKFxuICAgICAgICAoTG9hbi5vYmplY3RzLmZpbHRlcih0ZW5hbnQ9dGVuYW50KS5hZ2dyZWdhdGUodG90YWw9U3VtKCdhbW91bnQnKSlbJ3RvdGFsJ10gb3IgRGVjaW1hbCgnMCcpKVxuICAgICAgICAtIChMb2FuUmVwYXltZW50Lm9iamVjdHMuZmlsdGVyKHRlbmFudD10ZW5hbnQpLmFnZ3JlZ2F0ZSh0b3RhbD1TdW0oJ2Ftb3VudCcpKVsndG90YWwnXSBvciBEZWNpbWFsKCcwJykpXG4gICAgKVxuXG4gICAgbG9hbnNfdGFrZW5fcXMgPSBMb2FuLm9iamVjdHMuZmlsdGVyKHRlbmFudD10ZW5hbnQsIGRhdGVfX2d0ZT1zdGFydF9kYXRlLCBkYXRlX19sdGU9ZW5kX2RhdGUpXG4gICAgbG9hbl9yZXBheW1lbnRzX3FzID0gTG9hblJlcGF5bWVudC5vYmplY3RzLmZpbHRlcih0ZW5hbnQ9dGVuYW50LCBkYXRlX19ndGU9c3RhcnRfZGF0ZSwgZGF0ZV9fbHRlPWVuZF9kYXRlKVxuICAgIGxvYW5fbWFwID0ge31cbiAgICBmb3Igcm93IGluIGxvYW5zX3Rha2VuX3FzLnZhbHVlcygnc291cmNlJykuYW5ub3RhdGUodG90YWw9U3VtKCdhbW91bnQnKSwgY291bnQ9Q291bnQoJ2lkJykpOlxuICAgICAgICBlbnRyeSA9IGxvYW5fbWFwLnNldGRlZmF1bHQocm93Wydzb3VyY2UnXSwgeyd0YWtlbic6IERlY2ltYWwoJzAnKSwgJ3JlcGFpZCc6IERlY2ltYWwoJzAnKSwgJ2NvdW50JzogMH0pXG4gICAgICAgIGVudHJ5Wyd0YWtlbiddID0gcm93Wyd0b3RhbCddXG4gICAgICAgIGVudHJ5Wydjb3VudCddICs9IHJvd1snY291bnQnXVxuICAgIGZvciByb3cgaW4gbG9hbl9yZXBheW1lbnRzX3FzLnZhbHVlcygnbG9hbl9fc291cmNlJykuYW5ub3RhdGUodG90YWw9U3VtKCdhbW91bnQnKSwgY291bnQ9Q291bnQoJ2lkJykpOlxuICAgICAgICBlbnRyeSA9IGxvYW5fbWFwLnNldGRlZmF1bHQocm93Wydsb2FuX19zb3VyY2UnXSwgeyd0YWtlbic6IERlY2ltYWwoJzAnKSwgJ3JlcGFpZCc6IERlY2ltYWwoJzAnKSwgJ2NvdW50JzogMH0pXG4gICAgICAgIGVudHJ5WydyZXBhaWQnXSA9IHJvd1sndG90YWwnXVxuICAgICAgICBlbnRyeVsnY291bnQnXSArPSByb3dbJ2NvdW50J11cbiAgICBsb2FuX25hbWVzID0gc29ydGVkKGxvYW5fbWFwLmtleXMoKSlcbiAgICBsb2FuX2JyZWFrZG93biA9IFt7J25hbWUnOiBuLCAnbmV0JzogbG9hbl9tYXBbbl1bJ3Rha2VuJ10gLSBsb2FuX21hcFtuXVsncmVwYWlkJ10sICoqbG9hbl9tYXBbbl19IGZvciBuIGluIGxvYW5fbmFtZXNdXG4gICAgdG90YWxfcGVyaW9kX2xvYW5zX3Rha2VuID0gc3VtKChyb3dbJ3Rha2VuJ10gZm9yIHJvdyBpbiBsb2FuX2JyZWFrZG93biksIERlY2ltYWwoJzAnKSlcbiAgICB0b3RhbF9wZXJpb2RfbG9hbnNfcmVwYWlkID0gc3VtKChyb3dbJ3JlcGFpZCddIGZvciByb3cgaW4gbG9hbl9icmVha2Rvd24pLCBEZWNpbWFsKCcwJykpXG4gICAgY3VycmVudF9sb2Fuc19vdXRzdGFuZGluZyA9IChcbiAgICAgICAgKExvYW4ub2JqZWN0cy5maWx0ZXIodGVuYW50PXRlbmFudCkuYWdncmVnYXRlKHRvdGFsPVN1bSgnYW1vdW50JykpWyd0b3RhbCddIG9yIERlY2ltYWwoJzAnKSlcbiAgICAgICAgLSAoTG9hblJlcGF5bWVudC5vYmplY3RzLmZpbHRlcih0ZW5hbnQ9dGVuYW50KS5hZ2dyZWdhdGUodG90YWw9U3VtKCdhbW91bnQnKSlbJ3RvdGFsJ10gb3IgRGVjaW1hbCgnMCcpKVxuICAgIClcbiIsICJuZXciOiAiXG4gICAgbG9hbnNfdGFrZW5fcXMgPSBMb2FuLm9iamVjdHMuZmlsdGVyKHRlbmFudD10ZW5hbnQsIGRhdGVfX2d0ZT1zdGFydF9kYXRlLCBkYXRlX19sdGU9ZW5kX2RhdGUpXG4gICAgbG9hbl9yZXBheW1lbnRzX3FzID0gTG9hblJlcGF5bWVudC5vYmplY3RzLmZpbHRlcih0ZW5hbnQ9dGVuYW50LCBkYXRlX19ndGU9c3RhcnRfZGF0ZSwgZGF0ZV9fbHRlPWVuZF9kYXRlKVxuICAgIGxvYW5fbWFwID0ge31cbiAgICBmb3Igcm93IGluIGxvYW5zX3Rha2VuX3FzLnZhbHVlcygnc291cmNlJykuYW5ub3RhdGUodG90YWw9U3VtKCdhbW91bnQnKSwgY291bnQ9Q291bnQoJ2lkJykpOlxuICAgICAgICBlbnRyeSA9IGxvYW5fbWFwLnNldGRlZmF1bHQocm93Wydzb3VyY2UnXSwgeyd0YWtlbic6IERlY2ltYWwoJzAnKSwgJ3JlcGFpZCc6IERlY2ltYWwoJzAnKSwgJ2NvdW50JzogMH0pXG4gICAgICAgIGVudHJ5Wyd0YWtlbiddID0gcm93Wyd0b3RhbCddXG4gICAgICAgIGVudHJ5Wydjb3VudCddICs9IHJvd1snY291bnQnXVxuICAgIGZvciByb3cgaW4gbG9hbl9yZXBheW1lbnRzX3FzLnZhbHVlcygnbG9hbl9fc291cmNlJykuYW5ub3RhdGUodG90YWw9U3VtKCdhbW91bnQnKSwgY291bnQ9Q291bnQoJ2lkJykpOlxuICAgICAgICBlbnRyeSA9IGxvYW5fbWFwLnNldGRlZmF1bHQocm93Wydsb2FuX19zb3VyY2UnXSwgeyd0YWtlbic6IERlY2ltYWwoJzAnKSwgJ3JlcGFpZCc6IERlY2ltYWwoJzAnKSwgJ2NvdW50JzogMH0pXG4gICAgICAgIGVudHJ5WydyZXBhaWQnXSA9IHJvd1sndG90YWwnXVxuICAgICAgICBlbnRyeVsnY291bnQnXSArPSByb3dbJ2NvdW50J11cbiAgICBsb2FuX25hbWVzID0gc29ydGVkKGxvYW5fbWFwLmtleXMoKSlcbiAgICBsb2FuX2JyZWFrZG93biA9IFt7J25hbWUnOiBuLCAnbmV0JzogbG9hbl9tYXBbbl1bJ3Rha2VuJ10gLSBsb2FuX21hcFtuXVsncmVwYWlkJ10sICoqbG9hbl9tYXBbbl19IGZvciBuIGluIGxvYW5fbmFtZXNdXG4gICAgdG90YWxfcGVyaW9kX2xvYW5zX3Rha2VuID0gc3VtKChyb3dbJ3Rha2VuJ10gZm9yIHJvdyBpbiBsb2FuX2JyZWFrZG93biksIERlY2ltYWwoJzAnKSlcbiAgICB0b3RhbF9wZXJpb2RfbG9hbnNfcmVwYWlkID0gc3VtKChyb3dbJ3JlcGFpZCddIGZvciByb3cgaW4gbG9hbl9icmVha2Rvd24pLCBEZWNpbWFsKCcwJykpXG4gICAgY3VycmVudF9sb2Fuc19vdXRzdGFuZGluZyA9IChcbiAgICAgICAgKExvYW4ub2JqZWN0cy5maWx0ZXIodGVuYW50PXRlbmFudCkuYWdncmVnYXRlKHRvdGFsPVN1bSgnYW1vdW50JykpWyd0b3RhbCddIG9yIERlY2ltYWwoJzAnKSlcbiAgICAgICAgLSAoTG9hblJlcGF5bWVudC5vYmplY3RzLmZpbHRlcih0ZW5hbnQ9dGVuYW50KS5hZ2dyZWdhdGUodG90YWw9U3VtKCdhbW91bnQnKSlbJ3RvdGFsJ10gb3IgRGVjaW1hbCgnMCcpKVxuICAgIClcbiJ9LCB7InBhdGgiOiAidGVtcGxhdGVzL2xlZGdlci9kZXRhaWxfcmVwb3J0cy5odG1sIiwgIm9sZCI6ICIgICAgPGJ1dHRvbiBvbmNsaWNrPVwic2hvd0RldGFpbFRhYignbG9hbnMnKVwiIGlkPVwidGFiLWJ0bi1sb2Fuc1wiIGNsYXNzPVwidGFiLWJ0biBweC00IHB5LTIgdGV4dC1zbSBmb250LW1lZGl1bSByb3VuZGVkLWZ1bGwgYmctZ3JheS0xMDAgdGV4dC1ncmF5LTYwMCBob3ZlcjpiZy1ncmF5LTIwMCB3aGl0ZXNwYWNlLW5vd3JhcFwiPnslIHRyYW5zIFwiTG9hbnMgLyBCb3Jyb3dpbmdcIiAlfTwvYnV0dG9uPlxuICAgIDxidXR0b24gb25jbGljaz1cInNob3dEZXRhaWxUYWIoJ2xvYW5zJylcIiBpZD1cInRhYi1idG4tbG9hbnNcIiBjbGFzcz1cInRhYi1idG4gcHgtNCBweS0yIHRleHQtc20gZm9udC1tZWRpdW0gcm91bmRlZC1mdWxsIGJnLWdyYXktMTAwIHRleHQtZ3JheS02MDAgaG92ZXI6YmctZ3JheS0yMDAgd2hpdGVzcGFjZS1ub3dyYXBcIj57JSB0cmFucyBcIkxvYW5zIC8gQm9ycm93aW5nXCIgJX08L2J1dHRvbj5cbiIsICJuZXciOiAiICAgIDxidXR0b24gb25jbGljaz1cInNob3dEZXRhaWxUYWIoJ2xvYW5zJylcIiBpZD1cInRhYi1idG4tbG9hbnNcIiBjbGFzcz1cInRhYi1idG4gcHgtNCBweS0yIHRleHQtc20gZm9udC1tZWRpdW0gcm91bmRlZC1mdWxsIGJnLWdyYXktMTAwIHRleHQtZ3JheS02MDAgaG92ZXI6YmctZ3JheS0yMDAgd2hpdGVzcGFjZS1ub3dyYXBcIj57JSB0cmFucyBcIkxvYW5zIC8gQm9ycm93aW5nXCIgJX08L2J1dHRvbj5cbiJ9LCB7InBhdGgiOiAidGVtcGxhdGVzL2xlZGdlci9kZXRhaWxfcmVwb3J0cy5odG1sIiwgIm9sZCI6ICI8ZGl2IGlkPVwidGFiLWxvYW5zXCIgY2xhc3M9XCJ0YWItcGFuZWwgaGlkZGVuXCI+XG4gICAgPGRpdiBjbGFzcz1cImdyaWQgZ3JpZC1jb2xzLTMgZ2FwLTQgbWItNlwiPlxuICAgICAgICA8ZGl2IGNsYXNzPVwiYmctd2hpdGUgc2hhZG93IHJvdW5kZWQtbGcgcC00XCI+XG4gICAgICAgICAgICA8cCBjbGFzcz1cInRleHQteHMgdGV4dC1ncmF5LTUwMFwiPnslIHRyYW5zIFwiVGFrZW4gVGhpcyBQZXJpb2RcIiAlfTwvcD5cbiAgICAgICAgICAgIDxwIGNsYXNzPVwidGV4dC1sZyBmb250LXNlbWlib2xkIG10LTEgdGV4dC1hbWJlci02MDBcIj57eyBjdXJyZW5jeSB9fSB7eyB0b3RhbF9wZXJpb2RfbG9hbnNfdGFrZW58ZmxvYXRmb3JtYXQ6MiB9fTwvcD5cbiAgICAgICAgPC9kaXY+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJiZy13aGl0ZSBzaGFkb3cgcm91bmRlZC1sZyBwLTRcIj5cbiAgICAgICAgICAgIDxwIGNsYXNzPVwidGV4dC14cyB0ZXh0LWdyYXktNTAwXCI+eyUgdHJhbnMgXCJSZXBhaWQgVGhpcyBQZXJpb2RcIiAlfTwvcD5cbiAgICAgICAgICAgIDxwIGNsYXNzPVwidGV4dC1sZyBmb250LXNlbWlib2xkIG10LTEgdGV4dC1lbWVyYWxkLTYwMFwiPnt7IGN1cnJlbmN5IH19IHt7IHRvdGFsX3BlcmlvZF9sb2Fuc19yZXBhaWR8ZmxvYXRmb3JtYXQ6MiB9fTwvcD5cbiAgICAgICAgPC9kaXY+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJiZy13aGl0ZSBzaGFkb3cgcm91bmRlZC1sZyBwLTRcIj5cbiAgICAgICAgICAgIDxwIGNsYXNzPVwidGV4dC14cyB0ZXh0LWdyYXktNTAwXCI+eyUgdHJhbnMgXCJDdXJyZW50bHkgT3V0c3RhbmRpbmcgKGFsbC10aW1lKVwiICV9PC9wPlxuICAgICAgICAgICAgPHAgY2xhc3M9XCJ0ZXh0LWxnIGZvbnQtc2VtaWJvbGQgbXQtMSB0ZXh0LXJlZC02MDBcIj57eyBjdXJyZW5jeSB9fSB7eyBjdXJyZW50X2xvYW5zX291dHN0YW5kaW5nfGZsb2F0Zm9ybWF0OjIgfX08L3A+XG4gICAgICAgIDwvZGl2PlxuICAgIDwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJncmlkIGdyaWQtY29scy0xIG1kOmdyaWQtY29scy0yIGdhcC02IG1iLTZcIj5cbiAgICAgICAgPGRpdiBjbGFzcz1cImJnLXdoaXRlIHNoYWRvdyByb3VuZGVkLWxnIHAtNVwiPlxuICAgICAgICAgICAgPGRpdiBjbGFzcz1cImZsZXgganVzdGlmeS1iZXR3ZWVuIGl0ZW1zLWNlbnRlciBtYi0zXCI+XG4gICAgICAgICAgICAgICAgPGgyIGNsYXNzPVwiZm9udC1zZW1pYm9sZFwiPnslIHRyYW5zIFwiVGFrZW4gdnMgUmVwYWlkIGJ5IFNvdXJjZVwiICV9PC9oMj5cbiAgICAgICAgICAgICAgICB7JSBpZiBsb2FuX2xhYmVscyAlfTxidXR0b24gb25jbGljaz1cImRvd25sb2FkQ2hhcnQoJ2xvYW5zRGV0YWlsQ2hhcnQnLCdsb2Fucy1ieS1zb3VyY2UuanBnJylcIiBjbGFzcz1cIm5vLXByaW50IHRleHQteHMgdGV4dC1zbGF0ZS01MDAgaG92ZXI6dGV4dC1zbGF0ZS04MDAgdW5kZXJsaW5lXCI+eyUgdHJhbnMgXCJEb3dubG9hZCBKUEdcIiAlfTwvYnV0dG9uPnslIGVuZGlmICV9XG4gICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICAgIHslIGlmIGxvYW5fbGFiZWxzICV9PGNhbnZhcyBpZD1cImxvYW5zRGV0YWlsQ2hhcnRcIiBoZWlnaHQ9XCIyMjBcIj48L2NhbnZhcz57JSBlbHNlICV9PHAgY2xhc3M9XCJ0ZXh0LWdyYXktNDAwIHRleHQtc21cIj57JSB0cmFucyBcIk5vIGxvYW4gYWN0aXZpdHkgaW4gdGhpcyByYW5nZS5cIiAlfTwvcD57JSBlbmRpZiAlfVxuICAgICAgICA8L2Rpdj5cbiAgICAgICAgPGRpdiBjbGFzcz1cImJnLXdoaXRlIHNoYWRvdyByb3VuZGVkLWxnIHAtNSBvdmVyZmxvdy14LWF1dG9cIj5cbiAgICAgICAgICAgIDxoMiBjbGFzcz1cImZvbnQtc2VtaWJvbGQgbWItM1wiPnslIHRyYW5zIFwiQnJlYWtkb3duXCIgJX08L2gyPlxuICAgICAgICAgICAgPHRhYmxlIGNsYXNzPVwidy1mdWxsIHRleHQtc21cIj5cbiAgICAgICAgICAgICAgICA8dGhlYWQgY2xhc3M9XCJ0ZXh0LWxlZnQgdGV4dC1ncmF5LTUwMCBib3JkZXItYlwiPjx0cj48dGggY2xhc3M9XCJweS0yXCI+eyUgdHJhbnMgXCJTb3VyY2VcIiAlfTwvdGg+PHRoIGNsYXNzPVwidGV4dC1yaWdodFwiPnslIHRyYW5zIFwiVGFrZW5cIiAlfTwvdGg+PHRoIGNsYXNzPVwidGV4dC1yaWdodFwiPnslIHRyYW5zIFwiUmVwYWlkXCIgJX08L3RoPjx0aCBjbGFzcz1cInRleHQtcmlnaHRcIj57JSB0cmFucyBcIk5ldCAoYWRkZWQgdG8gY2FzaClcIiAlfTwvdGg+PC90cj48L3RoZWFkPlxuICAgICAgICAgICAgICAgIDx0Ym9keT5cbiAgICAgICAgICAgICAgICAgICAgeyUgZm9yIHJvdyBpbiBsb2FuX2JyZWFrZG93biAlfVxuICAgICAgICAgICAgICAgICAgICA8dHIgY2xhc3M9XCJib3JkZXItYiBsYXN0OmJvcmRlci0wXCI+XG4gICAgICAgICAgICAgICAgICAgICAgICA8dGQgY2xhc3M9XCJweS0yXCI+e3sgcm93Lm5hbWUgfX08L3RkPlxuICAgICAgICAgICAgICAgICAgICAgICAgPHRkIGNsYXNzPVwidGV4dC1yaWdodCB0ZXh0LWFtYmVyLTYwMFwiPnt7IGN1cnJlbmN5IH19IHt7IHJvdy50YWtlbiB9fTwvdGQ+XG4gICAgICAgICAgICAgICAgICAgICAgICA8dGQgY2xhc3M9XCJ0ZXh0LXJpZ2h0IHRleHQtZW1lcmFsZC02MDBcIj57eyBjdXJyZW5jeSB9fSB7eyByb3cucmVwYWlkIH19PC90ZD5cbiAgICAgICAgICAgICAgICAgICAgICAgIDx0ZCBjbGFzcz1cInRleHQtcmlnaHQgZm9udC1tZWRpdW1cIj57eyBjdXJyZW5jeSB9fSB7eyByb3cubmV0IH19PC90ZD5cbiAgICAgICAgICAgICAgICAgICAgPC90cj5cbiAgICAgICAgICAgICAgICAgICAgeyUgZW1wdHkgJX1cbiAgICAgICAgICAgICAgICAgICAgPHRyPjx0ZCBjb2xzcGFuPVwiNFwiIGNsYXNzPVwicHktNCB0ZXh0LWNlbnRlciB0ZXh0LWdyYXktNDAwXCI+eyUgdHJhbnMgXCJObyBsb2FuIGFjdGl2aXR5IGluIHRoaXMgcmFuZ2UuXCIgJX08L3RkPjwvdHI+XG4gICAgICAgICAgICAgICAgICAgIHslIGVuZGZvciAlfVxuICAgICAgICAgICAgICAgIDwvdGJvZHk+XG4gICAgICAgICAgICA8L3RhYmxlPlxuICAgICAgICA8L2Rpdj5cbiAgICA8L2Rpdj5cbiAgICA8cCBjbGFzcz1cInRleHQteHMgdGV4dC1ncmF5LTQwMFwiPnslIHRyYW5zIFwiTG9hbnMgdGFrZW4gYW5kIHJlcGF5bWVudHMgbmV2ZXIgYWZmZWN0IEluY29tZSBvciBFeHBlbnNlIHRvdGFscyBcdTIwMTQgdGhpcyB0YWIgaXMgc2hvd24gc2VwYXJhdGVseSBmb3IgcmVmZXJlbmNlLiBObyBpbnRlcmVzdCBpcyB0cmFja2VkLlwiICV9PC9wPlxuPC9kaXY+XG5cbjxkaXYgaWQ9XCJ0YWItbG9hbnNcIiBjbGFzcz1cInRhYi1wYW5lbCBoaWRkZW5cIj5cbiAgICA8ZGl2IGNsYXNzPVwiZ3JpZCBncmlkLWNvbHMtMyBnYXAtNCBtYi02XCI+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJiZy13aGl0ZSBzaGFkb3cgcm91bmRlZC1sZyBwLTRcIj5cbiAgICAgICAgICAgIDxwIGNsYXNzPVwidGV4dC14cyB0ZXh0LWdyYXktNTAwXCI+eyUgdHJhbnMgXCJUYWtlbiBUaGlzIFBlcmlvZFwiICV9PC9wPlxuICAgICAgICAgICAgPHAgY2xhc3M9XCJ0ZXh0LWxnIGZvbnQtc2VtaWJvbGQgbXQtMSB0ZXh0LWFtYmVyLTYwMFwiPnt7IGN1cnJlbmN5IH19IHt7IHRvdGFsX3BlcmlvZF9sb2Fuc190YWtlbnxmbG9hdGZvcm1hdDoyIH19PC9wPlxuICAgICAgICA8L2Rpdj5cbiAgICAgICAgPGRpdiBjbGFzcz1cImJnLXdoaXRlIHNoYWRvdyByb3VuZGVkLWxnIHAtNFwiPlxuICAgICAgICAgICAgPHAgY2xhc3M9XCJ0ZXh0LXhzIHRleHQtZ3JheS01MDBcIj57JSB0cmFucyBcIlJlcGFpZCBUaGlzIFBlcmlvZFwiICV9PC9wPlxuICAgICAgICAgICAgPHAgY2xhc3M9XCJ0ZXh0LWxnIGZvbnQtc2VtaWJvbGQgbXQtMSB0ZXh0LWVtZXJhbGQtNjAwXCI+e3sgY3VycmVuY3kgfX0ge3sgdG90YWxfcGVyaW9kX2xvYW5zX3JlcGFpZHxmbG9hdGZvcm1hdDoyIH19PC9wPlxuICAgICAgICA8L2Rpdj5cbiAgICAgICAgPGRpdiBjbGFzcz1cImJnLXdoaXRlIHNoYWRvdyByb3VuZGVkLWxnIHAtNFwiPlxuICAgICAgICAgICAgPHAgY2xhc3M9XCJ0ZXh0LXhzIHRleHQtZ3JheS01MDBcIj57JSB0cmFucyBcIkN1cnJlbnRseSBPdXRzdGFuZGluZyAoYWxsLXRpbWUpXCIgJX08L3A+XG4gICAgICAgICAgICA8cCBjbGFzcz1cInRleHQtbGcgZm9udC1zZW1pYm9sZCBtdC0xIHRleHQtcmVkLTYwMFwiPnt7IGN1cnJlbmN5IH19IHt7IGN1cnJlbnRfbG9hbnNfb3V0c3RhbmRpbmd8ZmxvYXRmb3JtYXQ6MiB9fTwvcD5cbiAgICAgICAgPC9kaXY+XG4gICAgPC9kaXY+XG4gICAgPGRpdiBjbGFzcz1cImdyaWQgZ3JpZC1jb2xzLTEgbWQ6Z3JpZC1jb2xzLTIgZ2FwLTYgbWItNlwiPlxuICAgICAgICA8ZGl2IGNsYXNzPVwiYmctd2hpdGUgc2hhZG93IHJvdW5kZWQtbGcgcC01XCI+XG4gICAgICAgICAgICA8ZGl2IGNsYXNzPVwiZmxleCBqdXN0aWZ5LWJldHdlZW4gaXRlbXMtY2VudGVyIG1iLTNcIj5cbiAgICAgICAgICAgICAgICA8aDIgY2xhc3M9XCJmb250LXNlbWlib2xkXCI+eyUgdHJhbnMgXCJUYWtlbiB2cyBSZXBhaWQgYnkgU291cmNlXCIgJX08L2gyPlxuICAgICAgICAgICAgICAgIHslIGlmIGxvYW5fbGFiZWxzICV9PGJ1dHRvbiBvbmNsaWNrPVwiZG93bmxvYWRDaGFydCgnbG9hbnNEZXRhaWxDaGFydCcsJ2xvYW5zLWJ5LXNvdXJjZS5qcGcnKVwiIGNsYXNzPVwibm8tcHJpbnQgdGV4dC14cyB0ZXh0LXNsYXRlLTUwMCBob3Zlcjp0ZXh0LXNsYXRlLTgwMCB1bmRlcmxpbmVcIj57JSB0cmFucyBcIkRvd25sb2FkIEpQR1wiICV9PC9idXR0b24+eyUgZW5kaWYgJX1cbiAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgICAgeyUgaWYgbG9hbl9sYWJlbHMgJX08Y2FudmFzIGlkPVwibG9hbnNEZXRhaWxDaGFydFwiIGhlaWdodD1cIjIyMFwiPjwvY2FudmFzPnslIGVsc2UgJX08cCBjbGFzcz1cInRleHQtZ3JheS00MDAgdGV4dC1zbVwiPnslIHRyYW5zIFwiTm8gbG9hbiBhY3Rpdml0eSBpbiB0aGlzIHJhbmdlLlwiICV9PC9wPnslIGVuZGlmICV9XG4gICAgICAgIDwvZGl2PlxuICAgICAgICA8ZGl2IGNsYXNzPVwiYmctd2hpdGUgc2hhZG93IHJvdW5kZWQtbGcgcC01IG92ZXJmbG93LXgtYXV0b1wiPlxuICAgICAgICAgICAgPGgyIGNsYXNzPVwiZm9udC1zZW1pYm9sZCBtYi0zXCI+eyUgdHJhbnMgXCJCcmVha2Rvd25cIiAlfTwvaDI+XG4gICAgICAgICAgICA8dGFibGUgY2xhc3M9XCJ3LWZ1bGwgdGV4dC1zbVwiPlxuICAgICAgICAgICAgICAgIDx0aGVhZCBjbGFzcz1cInRleHQtbGVmdCB0ZXh0LWdyYXktNTAwIGJvcmRlci1iXCI+PHRyPjx0aCBjbGFzcz1cInB5LTJcIj57JSB0cmFucyBcIlNvdXJjZVwiICV9PC90aD48dGggY2xhc3M9XCJ0ZXh0LXJpZ2h0XCI+eyUgdHJhbnMgXCJUYWtlblwiICV9PC90aD48dGggY2xhc3M9XCJ0ZXh0LXJpZ2h0XCI+eyUgdHJhbnMgXCJSZXBhaWRcIiAlfTwvdGg+PHRoIGNsYXNzPVwidGV4dC1yaWdodFwiPnslIHRyYW5zIFwiTmV0IChhZGRlZCB0byBjYXNoKVwiICV9PC90aD48L3RyPjwvdGhlYWQ+XG4gICAgICAgICAgICAgICAgPHRib2R5PlxuICAgICAgICAgICAgICAgICAgICB7JSBmb3Igcm93IGluIGxvYW5fYnJlYWtkb3duICV9XG4gICAgICAgICAgICAgICAgICAgIDx0ciBjbGFzcz1cImJvcmRlci1iIGxhc3Q6Ym9yZGVyLTBcIj5cbiAgICAgICAgICAgICAgICAgICAgICAgIDx0ZCBjbGFzcz1cInB5LTJcIj57eyByb3cubmFtZSB9fTwvdGQ+XG4gICAgICAgICAgICAgICAgICAgICAgICA8dGQgY2xhc3M9XCJ0ZXh0LXJpZ2h0IHRleHQtYW1iZXItNjAwXCI+e3sgY3VycmVuY3kgfX0ge3sgcm93LnRha2VuIH19PC90ZD5cbiAgICAgICAgICAgICAgICAgICAgICAgIDx0ZCBjbGFzcz1cInRleHQtcmlnaHQgdGV4dC1lbWVyYWxkLTYwMFwiPnt7IGN1cnJlbmN5IH19IHt7IHJvdy5yZXBhaWQgfX08L3RkPlxuICAgICAgICAgICAgICAgICAgICAgICAgPHRkIGNsYXNzPVwidGV4dC1yaWdodCBmb250LW1lZGl1bVwiPnt7IGN1cnJlbmN5IH19IHt7IHJvdy5uZXQgfX08L3RkPlxuICAgICAgICAgICAgICAgICAgICA8L3RyPlxuICAgICAgICAgICAgICAgICAgICB7JSBlbXB0eSAlfVxuICAgICAgICAgICAgICAgICAgICA8dHI+PHRkIGNvbHNwYW49XCI0XCIgY2xhc3M9XCJweS00IHRleHQtY2VudGVyIHRleHQtZ3JheS00MDBcIj57JSB0cmFucyBcIk5vIGxvYW4gYWN0aXZpdHkgaW4gdGhpcyByYW5nZS5cIiAlfTwvdGQ+PC90cj5cbiAgICAgICAgICAgICAgICAgICAgeyUgZW5kZm9yICV9XG4gICAgICAgICAgICAgICAgPC90Ym9keT5cbiAgICAgICAgICAgIDwvdGFibGU+XG4gICAgICAgIDwvZGl2PlxuICAgIDwvZGl2PlxuICAgIDxwIGNsYXNzPVwidGV4dC14cyB0ZXh0LWdyYXktNDAwXCI+eyUgdHJhbnMgXCJMb2FucyB0YWtlbiBhbmQgcmVwYXltZW50cyBuZXZlciBhZmZlY3QgSW5jb21lIG9yIEV4cGVuc2UgdG90YWxzIFx1MjAxNCB0aGlzIHRhYiBpcyBzaG93biBzZXBhcmF0ZWx5IGZvciByZWZlcmVuY2UuIE5vIGludGVyZXN0IGlzIHRyYWNrZWQuXCIgJX08L3A+XG48L2Rpdj5cblxuIiwgIm5ldyI6ICI8ZGl2IGlkPVwidGFiLWxvYW5zXCIgY2xhc3M9XCJ0YWItcGFuZWwgaGlkZGVuXCI+XG4gICAgPGRpdiBjbGFzcz1cImdyaWQgZ3JpZC1jb2xzLTMgZ2FwLTQgbWItNlwiPlxuICAgICAgICA8ZGl2IGNsYXNzPVwiYmctd2hpdGUgc2hhZG93IHJvdW5kZWQtbGcgcC00XCI+XG4gICAgICAgICAgICA8cCBjbGFzcz1cInRleHQteHMgdGV4dC1ncmF5LTUwMFwiPnslIHRyYW5zIFwiVGFrZW4gVGhpcyBQZXJpb2RcIiAlfTwvcD5cbiAgICAgICAgICAgIDxwIGNsYXNzPVwidGV4dC1sZyBmb250LXNlbWlib2xkIG10LTEgdGV4dC1hbWJlci02MDBcIj57eyBjdXJyZW5jeSB9fSB7eyB0b3RhbF9wZXJpb2RfbG9hbnNfdGFrZW58ZmxvYXRmb3JtYXQ6MiB9fTwvcD5cbiAgICAgICAgPC9kaXY+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJiZy13aGl0ZSBzaGFkb3cgcm91bmRlZC1sZyBwLTRcIj5cbiAgICAgICAgICAgIDxwIGNsYXNzPVwidGV4dC14cyB0ZXh0LWdyYXktNTAwXCI+eyUgdHJhbnMgXCJSZXBhaWQgVGhpcyBQZXJpb2RcIiAlfTwvcD5cbiAgICAgICAgICAgIDxwIGNsYXNzPVwidGV4dC1sZyBmb250LXNlbWlib2xkIG10LTEgdGV4dC1lbWVyYWxkLTYwMFwiPnt7IGN1cnJlbmN5IH19IHt7IHRvdGFsX3BlcmlvZF9sb2Fuc19yZXBhaWR8ZmxvYXRmb3JtYXQ6MiB9fTwvcD5cbiAgICAgICAgPC9kaXY+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJiZy13aGl0ZSBzaGFkb3cgcm91bmRlZC1sZyBwLTRcIj5cbiAgICAgICAgICAgIDxwIGNsYXNzPVwidGV4dC14cyB0ZXh0LWdyYXktNTAwXCI+eyUgdHJhbnMgXCJDdXJyZW50bHkgT3V0c3RhbmRpbmcgKGFsbC10aW1lKVwiICV9PC9wPlxuICAgICAgICAgICAgPHAgY2xhc3M9XCJ0ZXh0LWxnIGZvbnQtc2VtaWJvbGQgbXQtMSB0ZXh0LXJlZC02MDBcIj57eyBjdXJyZW5jeSB9fSB7eyBjdXJyZW50X2xvYW5zX291dHN0YW5kaW5nfGZsb2F0Zm9ybWF0OjIgfX08L3A+XG4gICAgICAgIDwvZGl2PlxuICAgIDwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJncmlkIGdyaWQtY29scy0xIG1kOmdyaWQtY29scy0yIGdhcC02IG1iLTZcIj5cbiAgICAgICAgPGRpdiBjbGFzcz1cImJnLXdoaXRlIHNoYWRvdyByb3VuZGVkLWxnIHAtNVwiPlxuICAgICAgICAgICAgPGRpdiBjbGFzcz1cImZsZXgganVzdGlmeS1iZXR3ZWVuIGl0ZW1zLWNlbnRlciBtYi0zXCI+XG4gICAgICAgICAgICAgICAgPGgyIGNsYXNzPVwiZm9udC1zZW1pYm9sZFwiPnslIHRyYW5zIFwiVGFrZW4gdnMgUmVwYWlkIGJ5IFNvdXJjZVwiICV9PC9oMj5cbiAgICAgICAgICAgICAgICB7JSBpZiBsb2FuX2xhYmVscyAlfTxidXR0b24gb25jbGljaz1cImRvd25sb2FkQ2hhcnQoJ2xvYW5zRGV0YWlsQ2hhcnQnLCdsb2Fucy1ieS1zb3VyY2UuanBnJylcIiBjbGFzcz1cIm5vLXByaW50IHRleHQteHMgdGV4dC1zbGF0ZS01MDAgaG92ZXI6dGV4dC1zbGF0ZS04MDAgdW5kZXJsaW5lXCI+eyUgdHJhbnMgXCJEb3dubG9hZCBKUEdcIiAlfTwvYnV0dG9uPnslIGVuZGlmICV9XG4gICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICAgIHslIGlmIGxvYW5fbGFiZWxzICV9PGNhbnZhcyBpZD1cImxvYW5zRGV0YWlsQ2hhcnRcIiBoZWlnaHQ9XCIyMjBcIj48L2NhbnZhcz57JSBlbHNlICV9PHAgY2xhc3M9XCJ0ZXh0LWdyYXktNDAwIHRleHQtc21cIj57JSB0cmFucyBcIk5vIGxvYW4gYWN0aXZpdHkgaW4gdGhpcyByYW5nZS5cIiAlfTwvcD57JSBlbmRpZiAlfVxuICAgICAgICA8L2Rpdj5cbiAgICAgICAgPGRpdiBjbGFzcz1cImJnLXdoaXRlIHNoYWRvdyByb3VuZGVkLWxnIHAtNSBvdmVyZmxvdy14LWF1dG9cIj5cbiAgICAgICAgICAgIDxoMiBjbGFzcz1cImZvbnQtc2VtaWJvbGQgbWItM1wiPnslIHRyYW5zIFwiQnJlYWtkb3duXCIgJX08L2gyPlxuICAgICAgICAgICAgPHRhYmxlIGNsYXNzPVwidy1mdWxsIHRleHQtc21cIj5cbiAgICAgICAgICAgICAgICA8dGhlYWQgY2xhc3M9XCJ0ZXh0LWxlZnQgdGV4dC1ncmF5LTUwMCBib3JkZXItYlwiPjx0cj48dGggY2xhc3M9XCJweS0yXCI+eyUgdHJhbnMgXCJTb3VyY2VcIiAlfTwvdGg+PHRoIGNsYXNzPVwidGV4dC1yaWdodFwiPnslIHRyYW5zIFwiVGFrZW5cIiAlfTwvdGg+PHRoIGNsYXNzPVwidGV4dC1yaWdodFwiPnslIHRyYW5zIFwiUmVwYWlkXCIgJX08L3RoPjx0aCBjbGFzcz1cInRleHQtcmlnaHRcIj57JSB0cmFucyBcIk5ldCAoYWRkZWQgdG8gY2FzaClcIiAlfTwvdGg+PC90cj48L3RoZWFkPlxuICAgICAgICAgICAgICAgIDx0Ym9keT5cbiAgICAgICAgICAgICAgICAgICAgeyUgZm9yIHJvdyBpbiBsb2FuX2JyZWFrZG93biAlfVxuICAgICAgICAgICAgICAgICAgICA8dHIgY2xhc3M9XCJib3JkZXItYiBsYXN0OmJvcmRlci0wXCI+XG4gICAgICAgICAgICAgICAgICAgICAgICA8dGQgY2xhc3M9XCJweS0yXCI+e3sgcm93Lm5hbWUgfX08L3RkPlxuICAgICAgICAgICAgICAgICAgICAgICAgPHRkIGNsYXNzPVwidGV4dC1yaWdodCB0ZXh0LWFtYmVyLTYwMFwiPnt7IGN1cnJlbmN5IH19IHt7IHJvdy50YWtlbiB9fTwvdGQ+XG4gICAgICAgICAgICAgICAgICAgICAgICA8dGQgY2xhc3M9XCJ0ZXh0LXJpZ2h0IHRleHQtZW1lcmFsZC02MDBcIj57eyBjdXJyZW5jeSB9fSB7eyByb3cucmVwYWlkIH19PC90ZD5cbiAgICAgICAgICAgICAgICAgICAgICAgIDx0ZCBjbGFzcz1cInRleHQtcmlnaHQgZm9udC1tZWRpdW1cIj57eyBjdXJyZW5jeSB9fSB7eyByb3cubmV0IH19PC90ZD5cbiAgICAgICAgICAgICAgICAgICAgPC90cj5cbiAgICAgICAgICAgICAgICAgICAgeyUgZW1wdHkgJX1cbiAgICAgICAgICAgICAgICAgICAgPHRyPjx0ZCBjb2xzcGFuPVwiNFwiIGNsYXNzPVwicHktNCB0ZXh0LWNlbnRlciB0ZXh0LWdyYXktNDAwXCI+eyUgdHJhbnMgXCJObyBsb2FuIGFjdGl2aXR5IGluIHRoaXMgcmFuZ2UuXCIgJX08L3RkPjwvdHI+XG4gICAgICAgICAgICAgICAgICAgIHslIGVuZGZvciAlfVxuICAgICAgICAgICAgICAgIDwvdGJvZHk+XG4gICAgICAgICAgICA8L3RhYmxlPlxuICAgICAgICA8L2Rpdj5cbiAgICA8L2Rpdj5cbiAgICA8cCBjbGFzcz1cInRleHQteHMgdGV4dC1ncmF5LTQwMFwiPnslIHRyYW5zIFwiTG9hbnMgdGFrZW4gYW5kIHJlcGF5bWVudHMgbmV2ZXIgYWZmZWN0IEluY29tZSBvciBFeHBlbnNlIHRvdGFscyBcdTIwMTQgdGhpcyB0YWIgaXMgc2hvd24gc2VwYXJhdGVseSBmb3IgcmVmZXJlbmNlLiBObyBpbnRlcmVzdCBpcyB0cmFja2VkLlwiICV9PC9wPlxuPC9kaXY+XG5cbiJ9LCB7InBhdGgiOiAidGVtcGxhdGVzL2xlZGdlci9kZXRhaWxfcmVwb3J0cy5odG1sIiwgIm9sZCI6ICJjb25zdCBsb2FuTGFiZWxzID0gSlNPTi5wYXJzZShkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnbG9hbi1sYWJlbHMnKS50ZXh0Q29udGVudCk7XG5jb25zdCBsb2FuVGFrZW5WYWx1ZXMgPSBKU09OLnBhcnNlKGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdsb2FuLXRha2VuLXZhbHVlcycpLnRleHRDb250ZW50KTtcbmNvbnN0IGxvYW5SZXBhaWRWYWx1ZXMgPSBKU09OLnBhcnNlKGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdsb2FuLXJlcGFpZC12YWx1ZXMnKS50ZXh0Q29udGVudCk7XG5pZiAobG9hbkxhYmVscy5sZW5ndGggPiAwKSB7XG4gICAgbmV3IENoYXJ0KGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdsb2Fuc0RldGFpbENoYXJ0JyksIHtcbiAgICAgICAgdHlwZTogJ2JhcicsXG4gICAgICAgIGRhdGE6IHtcbiAgICAgICAgICAgIGxhYmVsczogbG9hbkxhYmVscyxcbiAgICAgICAgICAgIGRhdGFzZXRzOiBbXG4gICAgICAgICAgICAgICAgeyBsYWJlbDogJ1Rha2VuJywgZGF0YTogbG9hblRha2VuVmFsdWVzLCBiYWNrZ3JvdW5kQ29sb3I6ICcjZjU5ZTBiJyB9LFxuICAgICAgICAgICAgICAgIHsgbGFiZWw6ICdSZXBhaWQnLCBkYXRhOiBsb2FuUmVwYWlkVmFsdWVzLCBiYWNrZ3JvdW5kQ29sb3I6ICcjMTBiOTgxJyB9LFxuICAgICAgICAgICAgXVxuICAgICAgICB9LFxuICAgICAgICBvcHRpb25zOiB7XG4gICAgICAgICAgICBwbHVnaW5zOiB7XG4gICAgICAgICAgICAgICAgbGVnZW5kOiB7IHBvc2l0aW9uOiAnYm90dG9tJyB9LFxuICAgICAgICAgICAgICAgIGRhdGFsYWJlbHM6IHsgY29sb3I6ICcjMTExJywgYW5jaG9yOiAnZW5kJywgYWxpZ246ICd0b3AnLCBmb250OiB7IHdlaWdodDogJ2JvbGQnLCBzaXplOiAxMCB9LCBmb3JtYXR0ZXI6IGZtdExhYmVsIH1cbiAgICAgICAgICAgIH1cbiAgICAgICAgfVxuICAgIH0pO1xufVxuXG5jb25zdCBsb2FuTGFiZWxzID0gSlNPTi5wYXJzZShkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnbG9hbi1sYWJlbHMnKS50ZXh0Q29udGVudCk7XG5jb25zdCBsb2FuVGFrZW5WYWx1ZXMgPSBKU09OLnBhcnNlKGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdsb2FuLXRha2VuLXZhbHVlcycpLnRleHRDb250ZW50KTtcbmNvbnN0IGxvYW5SZXBhaWRWYWx1ZXMgPSBKU09OLnBhcnNlKGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdsb2FuLXJlcGFpZC12YWx1ZXMnKS50ZXh0Q29udGVudCk7XG5pZiAobG9hbkxhYmVscy5sZW5ndGggPiAwKSB7XG4gICAgbmV3IENoYXJ0KGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdsb2Fuc0RldGFpbENoYXJ0JyksIHtcbiAgICAgICAgdHlwZTogJ2JhcicsXG4gICAgICAgIGRhdGE6IHtcbiAgICAgICAgICAgIGxhYmVsczogbG9hbkxhYmVscyxcbiAgICAgICAgICAgIGRhdGFzZXRzOiBbXG4gICAgICAgICAgICAgICAgeyBsYWJlbDogJ1Rha2VuJywgZGF0YTogbG9hblRha2VuVmFsdWVzLCBiYWNrZ3JvdW5kQ29sb3I6ICcjZjU5ZTBiJyB9LFxuICAgICAgICAgICAgICAgIHsgbGFiZWw6ICdSZXBhaWQnLCBkYXRhOiBsb2FuUmVwYWlkVmFsdWVzLCBiYWNrZ3JvdW5kQ29sb3I6ICcjMTBiOTgxJyB9LFxuICAgICAgICAgICAgXVxuICAgICAgICB9LFxuICAgICAgICBvcHRpb25zOiB7XG4gICAgICAgICAgICBwbHVnaW5zOiB7XG4gICAgICAgICAgICAgICAgbGVnZW5kOiB7IHBvc2l0aW9uOiAnYm90dG9tJyB9LFxuICAgICAgICAgICAgICAgIGRhdGFsYWJlbHM6IHsgY29sb3I6ICcjMTExJywgYW5jaG9yOiAnZW5kJywgYWxpZ246ICd0b3AnLCBmb250OiB7IHdlaWdodDogJ2JvbGQnLCBzaXplOiAxMCB9LCBmb3JtYXR0ZXI6IGZtdExhYmVsIH1cbiAgICAgICAgICAgIH1cbiAgICAgICAgfVxuICAgIH0pO1xufVxuXG4iLCAibmV3IjogImNvbnN0IGxvYW5MYWJlbHMgPSBKU09OLnBhcnNlKGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdsb2FuLWxhYmVscycpLnRleHRDb250ZW50KTtcbmNvbnN0IGxvYW5UYWtlblZhbHVlcyA9IEpTT04ucGFyc2UoZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2xvYW4tdGFrZW4tdmFsdWVzJykudGV4dENvbnRlbnQpO1xuY29uc3QgbG9hblJlcGFpZFZhbHVlcyA9IEpTT04ucGFyc2UoZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2xvYW4tcmVwYWlkLXZhbHVlcycpLnRleHRDb250ZW50KTtcbmlmIChsb2FuTGFiZWxzLmxlbmd0aCA+IDApIHtcbiAgICBuZXcgQ2hhcnQoZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2xvYW5zRGV0YWlsQ2hhcnQnKSwge1xuICAgICAgICB0eXBlOiAnYmFyJyxcbiAgICAgICAgZGF0YToge1xuICAgICAgICAgICAgbGFiZWxzOiBsb2FuTGFiZWxzLFxuICAgICAgICAgICAgZGF0YXNldHM6IFtcbiAgICAgICAgICAgICAgICB7IGxhYmVsOiAnVGFrZW4nLCBkYXRhOiBsb2FuVGFrZW5WYWx1ZXMsIGJhY2tncm91bmRDb2xvcjogJyNmNTllMGInIH0sXG4gICAgICAgICAgICAgICAgeyBsYWJlbDogJ1JlcGFpZCcsIGRhdGE6IGxvYW5SZXBhaWRWYWx1ZXMsIGJhY2tncm91bmRDb2xvcjogJyMxMGI5ODEnIH0sXG4gICAgICAgICAgICBdXG4gICAgICAgIH0sXG4gICAgICAgIG9wdGlvbnM6IHtcbiAgICAgICAgICAgIHBsdWdpbnM6IHtcbiAgICAgICAgICAgICAgICBsZWdlbmQ6IHsgcG9zaXRpb246ICdib3R0b20nIH0sXG4gICAgICAgICAgICAgICAgZGF0YWxhYmVsczogeyBjb2xvcjogJyMxMTEnLCBhbmNob3I6ICdlbmQnLCBhbGlnbjogJ3RvcCcsIGZvbnQ6IHsgd2VpZ2h0OiAnYm9sZCcsIHNpemU6IDEwIH0sIGZvcm1hdHRlcjogZm10TGFiZWwgfVxuICAgICAgICAgICAgfVxuICAgICAgICB9XG4gICAgfSk7XG59XG5cbiJ9XSwgImNyZWF0ZXMiOiB7fX0="""

manifest = json.loads(base64.b64decode(MANIFEST_B64).decode('utf-8'))

def patch(path, old, new, expect=1):
    with open(path, encoding='utf-8') as f:
        content = f.read()
    count = content.count(old)
    if count == 0:
        # old (the duplicated text) isn't there — already fixed, nothing to do.
        print(f"  [skip] {path}: duplication not found, already clean.")
        return
    if count != expect:
        print(f"  [FAIL] {path}: expected {expect} match(es) of the duplicated text, found {count}.")
        sys.exit(1)
    content = content.replace(old, new, 1)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"  [ok]   {path}: duplicate removed.")

for e in manifest['edits']:
    patch(e['path'], e['old'], e['new'])

print()
print("De-duplication complete.")
PYEOF
else
    echo "(skipped — nothing to patch)"
fi

echo
echo "== 5. Re-verify no duplication remains =="
BTN_COUNT=$(grep -c 'id="tab-btn-loans"' templates/ledger/detail_reports.html || true)
PANEL_COUNT=$(grep -c 'id="tab-loans"' templates/ledger/detail_reports.html || true)
CHART_COUNT=$(grep -c "const loanLabels" templates/ledger/detail_reports.html || true)
VIEWS_COUNT=$(grep -c "loans_taken_qs = Loan" ledger/views.py || true)
echo "  tab-btn-loans: $BTN_COUNT | tab-loans: $PANEL_COUNT | const loanLabels: $CHART_COUNT | views.py block: $VIEWS_COUNT"
if [ "$BTN_COUNT" -ne 1 ] || [ "$PANEL_COUNT" -ne 1 ] || [ "$CHART_COUNT" -ne 1 ] || [ "$VIEWS_COUNT" -ne 1 ]; then
    echo "!! Something is still off — expected exactly 1 of each. Stopping before commit."
    exit 1
fi
echo "  Confirmed: exactly one copy of everything."

echo
echo "== 6. Collect static =="
python manage.py collectstatic --noinput

echo
echo "== 7. Sanity check: Django can load the project =="
python manage.py check

echo
echo "== 8. Commit + push =="
git add -A
git status --short
git commit -m "Fix duplicate Loans/Borrowing tab content from patch_4 retry (removed JS SyntaxError that broke all report tabs)" --allow-empty
git push origin main

echo
echo "============================================================================"
echo "DONE. Duplication removed and verified (exactly 1 copy of each element)."
echo "Restart your app process now:"
echo "    sudo systemctl restart <your-gunicorn-service-name>"
echo "Then hard-refresh the Detail Reports page (Ctrl+Shift+R) and confirm:"
echo "  - Only ONE 'Loans / Borrowing' tab button"
echo "  - All tabs (Expense/Income/Payment/Savings/Loans) are clickable again"
echo "  - Charts render on every tab, not just Loans"
echo "Paste this script's full output back for verification."
echo "============================================================================"
