#!/usr/bin/env bash
# ============================================================================
# DailyLedger — Deploy Patch #4: Loans / Borrowing tab on Detail Reports
#
# Adds a "Loans / Borrowing" tab to the Detail Reports page, alongside the
# existing Expense/Income/Payment/Savings tabs — same style, same pattern.
# Shows: taken this period, repaid this period, currently outstanding
# (all-time), a per-source bar chart, and a breakdown table. Loans never
# affect Income/Expense totals, same as Savings.
#
# SAFETY: same as before — mandatory verified backup first, self-checking
# anchored edits (skip if already applied), verified end-to-end beforehand
# against your real code (correct per-source totals, correct period vs
# all-time figures, all template markers present).
#
# USAGE: paste this whole block directly into your SSH session.
# ============================================================================
set -euo pipefail

PROJECT_DIR="$HOME/dailyledger"
cd "$PROJECT_DIR"

echo "== 0. Pre-flight =="
if [ -d "venv" ]; then source venv/bin/activate; echo "Activated venv/"
elif [ -d ".venv" ]; then source .venv/bin/activate; echo "Activated .venv/"
else echo "WARNING: no venv/ found — using system python3."; fi

echo
echo "== 1. MANDATORY BACKUP (before touching anything) =="
DB_BACKUP_DIR="$PROJECT_DIR/backups/database"
PROJECT_BACKUP_DIR="$PROJECT_DIR/backups/project"

python manage.py run_backup --skip-notify

AFTER_DB_FILE=$(find "$DB_BACKUP_DIR" -name '*.sql.gz' -newermt '-2 minutes' 2>/dev/null | sort | tail -1)
AFTER_PROJ_FILE=$(find "$PROJECT_BACKUP_DIR" -name '*.tar.gz' -newermt '-2 minutes' 2>/dev/null | sort | tail -1)

if [ -z "$AFTER_DB_FILE" ] || [ ! -s "$AFTER_DB_FILE" ]; then
    echo "!! ABORT: no fresh, non-empty database backup file found — cannot verify backup succeeded."
    exit 1
fi
if [ -z "$AFTER_PROJ_FILE" ] || [ ! -s "$AFTER_PROJ_FILE" ]; then
    echo "!! ABORT: no fresh, non-empty project archive backup file found — cannot verify backup succeeded."
    exit 1
fi
echo "Backup verified:"
echo "  DB:      $AFTER_DB_FILE ($(du -h "$AFTER_DB_FILE" | cut -f1))"
echo "  Project: $AFTER_PROJ_FILE ($(du -h "$AFTER_PROJ_FILE" | cut -f1))"
echo "Safe to proceed."

echo
echo "== 2. Git status before patch =="
git status --short

echo
echo "== 3. Applying code patch =="
python3 - <<'PYEOF'
import base64, json, sys

MANIFEST_B64 = """
eyJlZGl0cyI6IFt7InBhdGgiOiAibGVkZ2VyL3ZpZXdzLnB5IiwgIm9sZCI6ICIgICAgc2F2aW5nc19uYW1lcyA9IHNvcnRlZChzYXZpbmdzX21hcC5rZXlzKCkpXG4gICAgc2F2aW5nc19icmVha2Rvd24gPSBbeyduYW1lJzogbiwgJ25ldCc6IHNhdmluZ3NfbWFwW25dWydkZXBvc2l0J10gLSBzYXZpbmdzX21hcFtuXVsnd2l0aGRyYXdhbCddLCAqKnNhdmluZ3NfbWFwW25dfSBmb3IgbiBpbiBzYXZpbmdzX25hbWVzXVxuICAgIHRvdGFsX3BlcmlvZF9kZXBvc2l0cyA9IHN1bSgocm93WydkZXBvc2l0J10gZm9yIHJvdyBpbiBzYXZpbmdzX2JyZWFrZG93biksIERlY2ltYWwoJzAnKSlcbiAgICB0b3RhbF9wZXJpb2Rfd2l0aGRyYXdhbHMgPSBzdW0oKHJvd1snd2l0aGRyYXdhbCddIGZvciByb3cgaW4gc2F2aW5nc19icmVha2Rvd24pLCBEZWNpbWFsKCcwJykpIiwgIm5ldyI6ICIgICAgc2F2aW5nc19uYW1lcyA9IHNvcnRlZChzYXZpbmdzX21hcC5rZXlzKCkpXG4gICAgc2F2aW5nc19icmVha2Rvd24gPSBbeyduYW1lJzogbiwgJ25ldCc6IHNhdmluZ3NfbWFwW25dWydkZXBvc2l0J10gLSBzYXZpbmdzX21hcFtuXVsnd2l0aGRyYXdhbCddLCAqKnNhdmluZ3NfbWFwW25dfSBmb3IgbiBpbiBzYXZpbmdzX25hbWVzXVxuICAgIHRvdGFsX3BlcmlvZF9kZXBvc2l0cyA9IHN1bSgocm93WydkZXBvc2l0J10gZm9yIHJvdyBpbiBzYXZpbmdzX2JyZWFrZG93biksIERlY2ltYWwoJzAnKSlcbiAgICB0b3RhbF9wZXJpb2Rfd2l0aGRyYXdhbHMgPSBzdW0oKHJvd1snd2l0aGRyYXdhbCddIGZvciByb3cgaW4gc2F2aW5nc19icmVha2Rvd24pLCBEZWNpbWFsKCcwJykpXG5cbiAgICBsb2Fuc190YWtlbl9xcyA9IExvYW4ub2JqZWN0cy5maWx0ZXIodGVuYW50PXRlbmFudCwgZGF0ZV9fZ3RlPXN0YXJ0X2RhdGUsIGRhdGVfX2x0ZT1lbmRfZGF0ZSlcbiAgICBsb2FuX3JlcGF5bWVudHNfcXMgPSBMb2FuUmVwYXltZW50Lm9iamVjdHMuZmlsdGVyKHRlbmFudD10ZW5hbnQsIGRhdGVfX2d0ZT1zdGFydF9kYXRlLCBkYXRlX19sdGU9ZW5kX2RhdGUpXG4gICAgbG9hbl9tYXAgPSB7fVxuICAgIGZvciByb3cgaW4gbG9hbnNfdGFrZW5fcXMudmFsdWVzKCdzb3VyY2UnKS5hbm5vdGF0ZSh0b3RhbD1TdW0oJ2Ftb3VudCcpLCBjb3VudD1Db3VudCgnaWQnKSk6XG4gICAgICAgIGVudHJ5ID0gbG9hbl9tYXAuc2V0ZGVmYXVsdChyb3dbJ3NvdXJjZSddLCB7J3Rha2VuJzogRGVjaW1hbCgnMCcpLCAncmVwYWlkJzogRGVjaW1hbCgnMCcpLCAnY291bnQnOiAwfSlcbiAgICAgICAgZW50cnlbJ3Rha2VuJ10gPSByb3dbJ3RvdGFsJ11cbiAgICAgICAgZW50cnlbJ2NvdW50J10gKz0gcm93Wydjb3VudCddXG4gICAgZm9yIHJvdyBpbiBsb2FuX3JlcGF5bWVudHNfcXMudmFsdWVzKCdsb2FuX19zb3VyY2UnKS5hbm5vdGF0ZSh0b3RhbD1TdW0oJ2Ftb3VudCcpLCBjb3VudD1Db3VudCgnaWQnKSk6XG4gICAgICAgIGVudHJ5ID0gbG9hbl9tYXAuc2V0ZGVmYXVsdChyb3dbJ2xvYW5fX3NvdXJjZSddLCB7J3Rha2VuJzogRGVjaW1hbCgnMCcpLCAncmVwYWlkJzogRGVjaW1hbCgnMCcpLCAnY291bnQnOiAwfSlcbiAgICAgICAgZW50cnlbJ3JlcGFpZCddID0gcm93Wyd0b3RhbCddXG4gICAgICAgIGVudHJ5Wydjb3VudCddICs9IHJvd1snY291bnQnXVxuICAgIGxvYW5fbmFtZXMgPSBzb3J0ZWQobG9hbl9tYXAua2V5cygpKVxuICAgIGxvYW5fYnJlYWtkb3duID0gW3snbmFtZSc6IG4sICduZXQnOiBsb2FuX21hcFtuXVsndGFrZW4nXSAtIGxvYW5fbWFwW25dWydyZXBhaWQnXSwgKipsb2FuX21hcFtuXX0gZm9yIG4gaW4gbG9hbl9uYW1lc11cbiAgICB0b3RhbF9wZXJpb2RfbG9hbnNfdGFrZW4gPSBzdW0oKHJvd1sndGFrZW4nXSBmb3Igcm93IGluIGxvYW5fYnJlYWtkb3duKSwgRGVjaW1hbCgnMCcpKVxuICAgIHRvdGFsX3BlcmlvZF9sb2Fuc19yZXBhaWQgPSBzdW0oKHJvd1sncmVwYWlkJ10gZm9yIHJvdyBpbiBsb2FuX2JyZWFrZG93biksIERlY2ltYWwoJzAnKSlcbiAgICBjdXJyZW50X2xvYW5zX291dHN0YW5kaW5nID0gKFxuICAgICAgICAoTG9hbi5vYmplY3RzLmZpbHRlcih0ZW5hbnQ9dGVuYW50KS5hZ2dyZWdhdGUodG90YWw9U3VtKCdhbW91bnQnKSlbJ3RvdGFsJ10gb3IgRGVjaW1hbCgnMCcpKVxuICAgICAgICAtIChMb2FuUmVwYXltZW50Lm9iamVjdHMuZmlsdGVyKHRlbmFudD10ZW5hbnQpLmFnZ3JlZ2F0ZSh0b3RhbD1TdW0oJ2Ftb3VudCcpKVsndG90YWwnXSBvciBEZWNpbWFsKCcwJykpXG4gICAgKSJ9LCB7InBhdGgiOiAibGVkZ2VyL3ZpZXdzLnB5IiwgIm9sZCI6ICIgICAgICAgICdzYXZpbmdzX2xhYmVscyc6IHNhdmluZ3NfbmFtZXMsXG4gICAgICAgICdzYXZpbmdzX2RlcG9zaXRfdmFsdWVzJzogW2Zsb2F0KHNhdmluZ3NfbWFwW25dWydkZXBvc2l0J10pIGZvciBuIGluIHNhdmluZ3NfbmFtZXNdLFxuICAgICAgICAnc2F2aW5nc193aXRoZHJhd2FsX3ZhbHVlcyc6IFtmbG9hdChzYXZpbmdzX21hcFtuXVsnd2l0aGRyYXdhbCddKSBmb3IgbiBpbiBzYXZpbmdzX25hbWVzXSxcbiAgICAgICAgJ2N1cnJlbmN5JzogdGVuYW50LmN1cnJlbmN5LFxuICAgIH0pIiwgIm5ldyI6ICIgICAgICAgICdzYXZpbmdzX2xhYmVscyc6IHNhdmluZ3NfbmFtZXMsXG4gICAgICAgICdzYXZpbmdzX2RlcG9zaXRfdmFsdWVzJzogW2Zsb2F0KHNhdmluZ3NfbWFwW25dWydkZXBvc2l0J10pIGZvciBuIGluIHNhdmluZ3NfbmFtZXNdLFxuICAgICAgICAnc2F2aW5nc193aXRoZHJhd2FsX3ZhbHVlcyc6IFtmbG9hdChzYXZpbmdzX21hcFtuXVsnd2l0aGRyYXdhbCddKSBmb3IgbiBpbiBzYXZpbmdzX25hbWVzXSxcbiAgICAgICAgJ2xvYW5fYnJlYWtkb3duJzogbG9hbl9icmVha2Rvd24sXG4gICAgICAgICd0b3RhbF9wZXJpb2RfbG9hbnNfdGFrZW4nOiB0b3RhbF9wZXJpb2RfbG9hbnNfdGFrZW4sXG4gICAgICAgICd0b3RhbF9wZXJpb2RfbG9hbnNfcmVwYWlkJzogdG90YWxfcGVyaW9kX2xvYW5zX3JlcGFpZCxcbiAgICAgICAgJ2N1cnJlbnRfbG9hbnNfb3V0c3RhbmRpbmcnOiBjdXJyZW50X2xvYW5zX291dHN0YW5kaW5nLFxuICAgICAgICAnbG9hbl9sYWJlbHMnOiBsb2FuX25hbWVzLFxuICAgICAgICAnbG9hbl90YWtlbl92YWx1ZXMnOiBbZmxvYXQobG9hbl9tYXBbbl1bJ3Rha2VuJ10pIGZvciBuIGluIGxvYW5fbmFtZXNdLFxuICAgICAgICAnbG9hbl9yZXBhaWRfdmFsdWVzJzogW2Zsb2F0KGxvYW5fbWFwW25dWydyZXBhaWQnXSkgZm9yIG4gaW4gbG9hbl9uYW1lc10sXG4gICAgICAgICdjdXJyZW5jeSc6IHRlbmFudC5jdXJyZW5jeSxcbiAgICB9KSJ9LCB7InBhdGgiOiAidGVtcGxhdGVzL2xlZGdlci9kZXRhaWxfcmVwb3J0cy5odG1sIiwgIm9sZCI6ICIgICAgPGJ1dHRvbiBvbmNsaWNrPVwic2hvd0RldGFpbFRhYignc2F2aW5ncycpXCIgaWQ9XCJ0YWItYnRuLXNhdmluZ3NcIiBjbGFzcz1cInRhYi1idG4gcHgtNCBweS0yIHRleHQtc20gZm9udC1tZWRpdW0gcm91bmRlZC1mdWxsIGJnLWdyYXktMTAwIHRleHQtZ3JheS02MDAgaG92ZXI6YmctZ3JheS0yMDAgd2hpdGVzcGFjZS1ub3dyYXBcIj57JSB0cmFucyBcIlNhdmluZ3NcIiAlfTwvYnV0dG9uPlxuIiwgIm5ldyI6ICIgICAgPGJ1dHRvbiBvbmNsaWNrPVwic2hvd0RldGFpbFRhYignc2F2aW5ncycpXCIgaWQ9XCJ0YWItYnRuLXNhdmluZ3NcIiBjbGFzcz1cInRhYi1idG4gcHgtNCBweS0yIHRleHQtc20gZm9udC1tZWRpdW0gcm91bmRlZC1mdWxsIGJnLWdyYXktMTAwIHRleHQtZ3JheS02MDAgaG92ZXI6YmctZ3JheS0yMDAgd2hpdGVzcGFjZS1ub3dyYXBcIj57JSB0cmFucyBcIlNhdmluZ3NcIiAlfTwvYnV0dG9uPlxuICAgIDxidXR0b24gb25jbGljaz1cInNob3dEZXRhaWxUYWIoJ2xvYW5zJylcIiBpZD1cInRhYi1idG4tbG9hbnNcIiBjbGFzcz1cInRhYi1idG4gcHgtNCBweS0yIHRleHQtc20gZm9udC1tZWRpdW0gcm91bmRlZC1mdWxsIGJnLWdyYXktMTAwIHRleHQtZ3JheS02MDAgaG92ZXI6YmctZ3JheS0yMDAgd2hpdGVzcGFjZS1ub3dyYXBcIj57JSB0cmFucyBcIkxvYW5zIC8gQm9ycm93aW5nXCIgJX08L2J1dHRvbj5cbiJ9LCB7InBhdGgiOiAidGVtcGxhdGVzL2xlZGdlci9kZXRhaWxfcmVwb3J0cy5odG1sIiwgIm9sZCI6ICIgICAgPHAgY2xhc3M9XCJ0ZXh0LXhzIHRleHQtZ3JheS00MDBcIj57JSB0cmFucyBcIlNhdmluZ3MgZGVwb3NpdHMgYW5kIHdpdGhkcmF3YWxzIG5ldmVyIGFmZmVjdCBJbmNvbWUgb3IgRXhwZW5zZSB0b3RhbHMgXHUyMDE0IHRoaXMgdGFiIGlzIHNob3duIHNlcGFyYXRlbHkgZm9yIHJlZmVyZW5jZS5cIiAlfTwvcD5cbjwvZGl2PlxuXG4iLCAibmV3IjogIiAgICA8cCBjbGFzcz1cInRleHQteHMgdGV4dC1ncmF5LTQwMFwiPnslIHRyYW5zIFwiU2F2aW5ncyBkZXBvc2l0cyBhbmQgd2l0aGRyYXdhbHMgbmV2ZXIgYWZmZWN0IEluY29tZSBvciBFeHBlbnNlIHRvdGFscyBcdTIwMTQgdGhpcyB0YWIgaXMgc2hvd24gc2VwYXJhdGVseSBmb3IgcmVmZXJlbmNlLlwiICV9PC9wPlxuPC9kaXY+XG5cbjxkaXYgaWQ9XCJ0YWItbG9hbnNcIiBjbGFzcz1cInRhYi1wYW5lbCBoaWRkZW5cIj5cbiAgICA8ZGl2IGNsYXNzPVwiZ3JpZCBncmlkLWNvbHMtMyBnYXAtNCBtYi02XCI+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJiZy13aGl0ZSBzaGFkb3cgcm91bmRlZC1sZyBwLTRcIj5cbiAgICAgICAgICAgIDxwIGNsYXNzPVwidGV4dC14cyB0ZXh0LWdyYXktNTAwXCI+eyUgdHJhbnMgXCJUYWtlbiBUaGlzIFBlcmlvZFwiICV9PC9wPlxuICAgICAgICAgICAgPHAgY2xhc3M9XCJ0ZXh0LWxnIGZvbnQtc2VtaWJvbGQgbXQtMSB0ZXh0LWFtYmVyLTYwMFwiPnt7IGN1cnJlbmN5IH19IHt7IHRvdGFsX3BlcmlvZF9sb2Fuc190YWtlbnxmbG9hdGZvcm1hdDoyIH19PC9wPlxuICAgICAgICA8L2Rpdj5cbiAgICAgICAgPGRpdiBjbGFzcz1cImJnLXdoaXRlIHNoYWRvdyByb3VuZGVkLWxnIHAtNFwiPlxuICAgICAgICAgICAgPHAgY2xhc3M9XCJ0ZXh0LXhzIHRleHQtZ3JheS01MDBcIj57JSB0cmFucyBcIlJlcGFpZCBUaGlzIFBlcmlvZFwiICV9PC9wPlxuICAgICAgICAgICAgPHAgY2xhc3M9XCJ0ZXh0LWxnIGZvbnQtc2VtaWJvbGQgbXQtMSB0ZXh0LWVtZXJhbGQtNjAwXCI+e3sgY3VycmVuY3kgfX0ge3sgdG90YWxfcGVyaW9kX2xvYW5zX3JlcGFpZHxmbG9hdGZvcm1hdDoyIH19PC9wPlxuICAgICAgICA8L2Rpdj5cbiAgICAgICAgPGRpdiBjbGFzcz1cImJnLXdoaXRlIHNoYWRvdyByb3VuZGVkLWxnIHAtNFwiPlxuICAgICAgICAgICAgPHAgY2xhc3M9XCJ0ZXh0LXhzIHRleHQtZ3JheS01MDBcIj57JSB0cmFucyBcIkN1cnJlbnRseSBPdXRzdGFuZGluZyAoYWxsLXRpbWUpXCIgJX08L3A+XG4gICAgICAgICAgICA8cCBjbGFzcz1cInRleHQtbGcgZm9udC1zZW1pYm9sZCBtdC0xIHRleHQtcmVkLTYwMFwiPnt7IGN1cnJlbmN5IH19IHt7IGN1cnJlbnRfbG9hbnNfb3V0c3RhbmRpbmd8ZmxvYXRmb3JtYXQ6MiB9fTwvcD5cbiAgICAgICAgPC9kaXY+XG4gICAgPC9kaXY+XG4gICAgPGRpdiBjbGFzcz1cImdyaWQgZ3JpZC1jb2xzLTEgbWQ6Z3JpZC1jb2xzLTIgZ2FwLTYgbWItNlwiPlxuICAgICAgICA8ZGl2IGNsYXNzPVwiYmctd2hpdGUgc2hhZG93IHJvdW5kZWQtbGcgcC01XCI+XG4gICAgICAgICAgICA8ZGl2IGNsYXNzPVwiZmxleCBqdXN0aWZ5LWJldHdlZW4gaXRlbXMtY2VudGVyIG1iLTNcIj5cbiAgICAgICAgICAgICAgICA8aDIgY2xhc3M9XCJmb250LXNlbWlib2xkXCI+eyUgdHJhbnMgXCJUYWtlbiB2cyBSZXBhaWQgYnkgU291cmNlXCIgJX08L2gyPlxuICAgICAgICAgICAgICAgIHslIGlmIGxvYW5fbGFiZWxzICV9PGJ1dHRvbiBvbmNsaWNrPVwiZG93bmxvYWRDaGFydCgnbG9hbnNEZXRhaWxDaGFydCcsJ2xvYW5zLWJ5LXNvdXJjZS5qcGcnKVwiIGNsYXNzPVwibm8tcHJpbnQgdGV4dC14cyB0ZXh0LXNsYXRlLTUwMCBob3Zlcjp0ZXh0LXNsYXRlLTgwMCB1bmRlcmxpbmVcIj57JSB0cmFucyBcIkRvd25sb2FkIEpQR1wiICV9PC9idXR0b24+eyUgZW5kaWYgJX1cbiAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgICAgeyUgaWYgbG9hbl9sYWJlbHMgJX08Y2FudmFzIGlkPVwibG9hbnNEZXRhaWxDaGFydFwiIGhlaWdodD1cIjIyMFwiPjwvY2FudmFzPnslIGVsc2UgJX08cCBjbGFzcz1cInRleHQtZ3JheS00MDAgdGV4dC1zbVwiPnslIHRyYW5zIFwiTm8gbG9hbiBhY3Rpdml0eSBpbiB0aGlzIHJhbmdlLlwiICV9PC9wPnslIGVuZGlmICV9XG4gICAgICAgIDwvZGl2PlxuICAgICAgICA8ZGl2IGNsYXNzPVwiYmctd2hpdGUgc2hhZG93IHJvdW5kZWQtbGcgcC01IG92ZXJmbG93LXgtYXV0b1wiPlxuICAgICAgICAgICAgPGgyIGNsYXNzPVwiZm9udC1zZW1pYm9sZCBtYi0zXCI+eyUgdHJhbnMgXCJCcmVha2Rvd25cIiAlfTwvaDI+XG4gICAgICAgICAgICA8dGFibGUgY2xhc3M9XCJ3LWZ1bGwgdGV4dC1zbVwiPlxuICAgICAgICAgICAgICAgIDx0aGVhZCBjbGFzcz1cInRleHQtbGVmdCB0ZXh0LWdyYXktNTAwIGJvcmRlci1iXCI+PHRyPjx0aCBjbGFzcz1cInB5LTJcIj57JSB0cmFucyBcIlNvdXJjZVwiICV9PC90aD48dGggY2xhc3M9XCJ0ZXh0LXJpZ2h0XCI+eyUgdHJhbnMgXCJUYWtlblwiICV9PC90aD48dGggY2xhc3M9XCJ0ZXh0LXJpZ2h0XCI+eyUgdHJhbnMgXCJSZXBhaWRcIiAlfTwvdGg+PHRoIGNsYXNzPVwidGV4dC1yaWdodFwiPnslIHRyYW5zIFwiTmV0IChhZGRlZCB0byBjYXNoKVwiICV9PC90aD48L3RyPjwvdGhlYWQ+XG4gICAgICAgICAgICAgICAgPHRib2R5PlxuICAgICAgICAgICAgICAgICAgICB7JSBmb3Igcm93IGluIGxvYW5fYnJlYWtkb3duICV9XG4gICAgICAgICAgICAgICAgICAgIDx0ciBjbGFzcz1cImJvcmRlci1iIGxhc3Q6Ym9yZGVyLTBcIj5cbiAgICAgICAgICAgICAgICAgICAgICAgIDx0ZCBjbGFzcz1cInB5LTJcIj57eyByb3cubmFtZSB9fTwvdGQ+XG4gICAgICAgICAgICAgICAgICAgICAgICA8dGQgY2xhc3M9XCJ0ZXh0LXJpZ2h0IHRleHQtYW1iZXItNjAwXCI+e3sgY3VycmVuY3kgfX0ge3sgcm93LnRha2VuIH19PC90ZD5cbiAgICAgICAgICAgICAgICAgICAgICAgIDx0ZCBjbGFzcz1cInRleHQtcmlnaHQgdGV4dC1lbWVyYWxkLTYwMFwiPnt7IGN1cnJlbmN5IH19IHt7IHJvdy5yZXBhaWQgfX08L3RkPlxuICAgICAgICAgICAgICAgICAgICAgICAgPHRkIGNsYXNzPVwidGV4dC1yaWdodCBmb250LW1lZGl1bVwiPnt7IGN1cnJlbmN5IH19IHt7IHJvdy5uZXQgfX08L3RkPlxuICAgICAgICAgICAgICAgICAgICA8L3RyPlxuICAgICAgICAgICAgICAgICAgICB7JSBlbXB0eSAlfVxuICAgICAgICAgICAgICAgICAgICA8dHI+PHRkIGNvbHNwYW49XCI0XCIgY2xhc3M9XCJweS00IHRleHQtY2VudGVyIHRleHQtZ3JheS00MDBcIj57JSB0cmFucyBcIk5vIGxvYW4gYWN0aXZpdHkgaW4gdGhpcyByYW5nZS5cIiAlfTwvdGQ+PC90cj5cbiAgICAgICAgICAgICAgICAgICAgeyUgZW5kZm9yICV9XG4gICAgICAgICAgICAgICAgPC90Ym9keT5cbiAgICAgICAgICAgIDwvdGFibGU+XG4gICAgICAgIDwvZGl2PlxuICAgIDwvZGl2PlxuICAgIDxwIGNsYXNzPVwidGV4dC14cyB0ZXh0LWdyYXktNDAwXCI+eyUgdHJhbnMgXCJMb2FucyB0YWtlbiBhbmQgcmVwYXltZW50cyBuZXZlciBhZmZlY3QgSW5jb21lIG9yIEV4cGVuc2UgdG90YWxzIFx1MjAxNCB0aGlzIHRhYiBpcyBzaG93biBzZXBhcmF0ZWx5IGZvciByZWZlcmVuY2UuIE5vIGludGVyZXN0IGlzIHRyYWNrZWQuXCIgJX08L3A+XG48L2Rpdj5cblxuIn0sIHsicGF0aCI6ICJ0ZW1wbGF0ZXMvbGVkZ2VyL2RldGFpbF9yZXBvcnRzLmh0bWwiLCAib2xkIjogInt7IHNhdmluZ3NfbGFiZWxzfGpzb25fc2NyaXB0Olwic2F2aW5ncy1sYWJlbHNcIiB9fVxue3sgc2F2aW5nc19kZXBvc2l0X3ZhbHVlc3xqc29uX3NjcmlwdDpcInNhdmluZ3MtZGVwb3NpdC12YWx1ZXNcIiB9fVxue3sgc2F2aW5nc193aXRoZHJhd2FsX3ZhbHVlc3xqc29uX3NjcmlwdDpcInNhdmluZ3Mtd2l0aGRyYXdhbC12YWx1ZXNcIiB9fVxue3sgY3VycmVuY3l8anNvbl9zY3JpcHQ6XCJjdXJyZW5jeS1jb2RlXCIgfX0iLCAibmV3IjogInt7IHNhdmluZ3NfbGFiZWxzfGpzb25fc2NyaXB0Olwic2F2aW5ncy1sYWJlbHNcIiB9fVxue3sgc2F2aW5nc19kZXBvc2l0X3ZhbHVlc3xqc29uX3NjcmlwdDpcInNhdmluZ3MtZGVwb3NpdC12YWx1ZXNcIiB9fVxue3sgc2F2aW5nc193aXRoZHJhd2FsX3ZhbHVlc3xqc29uX3NjcmlwdDpcInNhdmluZ3Mtd2l0aGRyYXdhbC12YWx1ZXNcIiB9fVxue3sgbG9hbl9sYWJlbHN8anNvbl9zY3JpcHQ6XCJsb2FuLWxhYmVsc1wiIH19XG57eyBsb2FuX3Rha2VuX3ZhbHVlc3xqc29uX3NjcmlwdDpcImxvYW4tdGFrZW4tdmFsdWVzXCIgfX1cbnt7IGxvYW5fcmVwYWlkX3ZhbHVlc3xqc29uX3NjcmlwdDpcImxvYW4tcmVwYWlkLXZhbHVlc1wiIH19XG57eyBjdXJyZW5jeXxqc29uX3NjcmlwdDpcImN1cnJlbmN5LWNvZGVcIiB9fSJ9LCB7InBhdGgiOiAidGVtcGxhdGVzL2xlZGdlci9kZXRhaWxfcmVwb3J0cy5odG1sIiwgIm9sZCI6ICJpZiAoc2F2aW5nc0xhYmVscy5sZW5ndGggPiAwKSB7XG4gICAgbmV3IENoYXJ0KGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdzYXZpbmdzRGV0YWlsQ2hhcnQnKSwge1xuICAgICAgICB0eXBlOiAnYmFyJyxcbiAgICAgICAgZGF0YToge1xuICAgICAgICAgICAgbGFiZWxzOiBzYXZpbmdzTGFiZWxzLFxuICAgICAgICAgICAgZGF0YXNldHM6IFtcbiAgICAgICAgICAgICAgICB7IGxhYmVsOiAnRGVwb3NpdGVkJywgZGF0YTogc2F2aW5nc0RlcG9zaXRWYWx1ZXMsIGJhY2tncm91bmRDb2xvcjogJyNmNTllMGInIH0sXG4gICAgICAgICAgICAgICAgeyBsYWJlbDogJ1dpdGhkcmF3bicsIGRhdGE6IHNhdmluZ3NXaXRoZHJhd2FsVmFsdWVzLCBiYWNrZ3JvdW5kQ29sb3I6ICcjMTBiOTgxJyB9LFxuICAgICAgICAgICAgXVxuICAgICAgICB9LFxuICAgICAgICBvcHRpb25zOiB7XG4gICAgICAgICAgICBwbHVnaW5zOiB7XG4gICAgICAgICAgICAgICAgbGVnZW5kOiB7IHBvc2l0aW9uOiAnYm90dG9tJyB9LFxuICAgICAgICAgICAgICAgIGRhdGFsYWJlbHM6IHsgY29sb3I6ICcjMTExJywgYW5jaG9yOiAnZW5kJywgYWxpZ246ICd0b3AnLCBmb250OiB7IHdlaWdodDogJ2JvbGQnLCBzaXplOiAxMCB9LCBmb3JtYXR0ZXI6IGZtdExhYmVsIH1cbiAgICAgICAgICAgIH1cbiAgICAgICAgfVxuICAgIH0pO1xufSIsICJuZXciOiAiaWYgKHNhdmluZ3NMYWJlbHMubGVuZ3RoID4gMCkge1xuICAgIG5ldyBDaGFydChkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnc2F2aW5nc0RldGFpbENoYXJ0JyksIHtcbiAgICAgICAgdHlwZTogJ2JhcicsXG4gICAgICAgIGRhdGE6IHtcbiAgICAgICAgICAgIGxhYmVsczogc2F2aW5nc0xhYmVscyxcbiAgICAgICAgICAgIGRhdGFzZXRzOiBbXG4gICAgICAgICAgICAgICAgeyBsYWJlbDogJ0RlcG9zaXRlZCcsIGRhdGE6IHNhdmluZ3NEZXBvc2l0VmFsdWVzLCBiYWNrZ3JvdW5kQ29sb3I6ICcjZjU5ZTBiJyB9LFxuICAgICAgICAgICAgICAgIHsgbGFiZWw6ICdXaXRoZHJhd24nLCBkYXRhOiBzYXZpbmdzV2l0aGRyYXdhbFZhbHVlcywgYmFja2dyb3VuZENvbG9yOiAnIzEwYjk4MScgfSxcbiAgICAgICAgICAgIF1cbiAgICAgICAgfSxcbiAgICAgICAgb3B0aW9uczoge1xuICAgICAgICAgICAgcGx1Z2luczoge1xuICAgICAgICAgICAgICAgIGxlZ2VuZDogeyBwb3NpdGlvbjogJ2JvdHRvbScgfSxcbiAgICAgICAgICAgICAgICBkYXRhbGFiZWxzOiB7IGNvbG9yOiAnIzExMScsIGFuY2hvcjogJ2VuZCcsIGFsaWduOiAndG9wJywgZm9udDogeyB3ZWlnaHQ6ICdib2xkJywgc2l6ZTogMTAgfSwgZm9ybWF0dGVyOiBmbXRMYWJlbCB9XG4gICAgICAgICAgICB9XG4gICAgICAgIH1cbiAgICB9KTtcbn1cblxuY29uc3QgbG9hbkxhYmVscyA9IEpTT04ucGFyc2UoZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2xvYW4tbGFiZWxzJykudGV4dENvbnRlbnQpO1xuY29uc3QgbG9hblRha2VuVmFsdWVzID0gSlNPTi5wYXJzZShkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnbG9hbi10YWtlbi12YWx1ZXMnKS50ZXh0Q29udGVudCk7XG5jb25zdCBsb2FuUmVwYWlkVmFsdWVzID0gSlNPTi5wYXJzZShkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnbG9hbi1yZXBhaWQtdmFsdWVzJykudGV4dENvbnRlbnQpO1xuaWYgKGxvYW5MYWJlbHMubGVuZ3RoID4gMCkge1xuICAgIG5ldyBDaGFydChkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnbG9hbnNEZXRhaWxDaGFydCcpLCB7XG4gICAgICAgIHR5cGU6ICdiYXInLFxuICAgICAgICBkYXRhOiB7XG4gICAgICAgICAgICBsYWJlbHM6IGxvYW5MYWJlbHMsXG4gICAgICAgICAgICBkYXRhc2V0czogW1xuICAgICAgICAgICAgICAgIHsgbGFiZWw6ICdUYWtlbicsIGRhdGE6IGxvYW5UYWtlblZhbHVlcywgYmFja2dyb3VuZENvbG9yOiAnI2Y1OWUwYicgfSxcbiAgICAgICAgICAgICAgICB7IGxhYmVsOiAnUmVwYWlkJywgZGF0YTogbG9hblJlcGFpZFZhbHVlcywgYmFja2dyb3VuZENvbG9yOiAnIzEwYjk4MScgfSxcbiAgICAgICAgICAgIF1cbiAgICAgICAgfSxcbiAgICAgICAgb3B0aW9uczoge1xuICAgICAgICAgICAgcGx1Z2luczoge1xuICAgICAgICAgICAgICAgIGxlZ2VuZDogeyBwb3NpdGlvbjogJ2JvdHRvbScgfSxcbiAgICAgICAgICAgICAgICBkYXRhbGFiZWxzOiB7IGNvbG9yOiAnIzExMScsIGFuY2hvcjogJ2VuZCcsIGFsaWduOiAndG9wJywgZm9udDogeyB3ZWlnaHQ6ICdib2xkJywgc2l6ZTogMTAgfSwgZm9ybWF0dGVyOiBmbXRMYWJlbCB9XG4gICAgICAgICAgICB9XG4gICAgICAgIH1cbiAgICB9KTtcbn0ifV0sICJjcmVhdGVzIjoge319"""

manifest = json.loads(base64.b64decode(MANIFEST_B64).decode('utf-8'))

def patch(path, old, new, expect=1):
    with open(path, encoding='utf-8') as f:
        content = f.read()
    count = content.count(old)
    if count == 0 and content.count(new) > 0:
        print(f"  [skip] {path}: already applied.")
        return
    if count != expect:
        print(f"  [FAIL] {path}: expected {expect} match(es) of anchor, found {count}.")
        sys.exit(1)
    content = content.replace(old, new, 1)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"  [ok]   {path}: patched.")

for e in manifest['edits']:
    patch(e['path'], e['old'], e['new'])

print()
print("All edits applied.")
PYEOF

echo
echo "== 4. No migration needed (view/template only, no model changes) =="

echo
echo "== 5. Collect static =="
python manage.py collectstatic --noinput

echo
echo "== 6. Sanity check: Django can load the project =="
python manage.py check

echo
echo "== 7. Commit + push =="
git add -A
git status --short
git commit -m "Add Loans/Borrowing tab to Detail Reports page (taken/repaid/outstanding, per-source breakdown + chart)"
git push origin main

echo
echo "============================================================================"
echo "DONE. Backup verified before any changes. Code committed, pushed, and"
echo "checked clean. No migration was needed (view/template-only change)."
echo "Restart your app process now:"
echo "    sudo systemctl restart <your-gunicorn-service-name>"
echo "Then check: Detail Reports page has a new 'Loans / Borrowing' tab next"
echo "to Savings."
echo "Paste this script's full output back for verification."
echo "============================================================================"
