# Generated by Django 5.2.17 on 2026-08-18 04:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageViewCounter',
            fields=[
                ('id', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('count', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('USER_REGISTER', 'User Registered'), ('USER_APPROVED', 'User Approved'), ('USER_REJECTED', 'User Rejected'), ('TRANSACTION_CREATE', 'Transaction Created'), ('TRANSACTION_UPDATE', 'Transaction Updated'), ('TRANSACTION_DELETE', 'Transaction Deleted'), ('BUDGET_CREATE', 'Budget Created'), ('BUDGET_DELETE', 'Budget Deleted')], max_length=30)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', 'action'], name='accounts_au_actor_i_6ce129_idx'), models.Index(fields=['created_at'], name='accounts_au_created_606b86_idx')],
            },
        ),
    ]
