# Generated by Django 5.2.17 on 2026-08-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pageviewcounter_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='setup_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('USER_REGISTER', 'User Registered'), ('USER_APPROVED', 'User Approved'), ('USER_REJECTED', 'User Rejected'), ('SETUP_COMPLETED', 'Setup Completed'), ('TRANSACTION_CREATE', 'Transaction Created'), ('TRANSACTION_UPDATE', 'Transaction Updated'), ('TRANSACTION_DELETE', 'Transaction Deleted'), ('BUDGET_CREATE', 'Budget Created'), ('BUDGET_DELETE', 'Budget Deleted')], max_length=30),
        ),
    ]
