# Generated by Django 5.2.17 on 2026-08-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tenant_setup_completed_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=10),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('USER_REGISTER', 'User Registered'), ('USER_APPROVED', 'User Approved'), ('USER_REJECTED', 'User Rejected'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_REACTIVATED', 'User Reactivated'), ('PASSWORD_CHANGE', 'Password Changed'), ('SETUP_COMPLETED', 'Setup Completed'), ('TRANSACTION_CREATE', 'Transaction Created'), ('TRANSACTION_UPDATE', 'Transaction Updated'), ('TRANSACTION_DELETE', 'Transaction Deleted'), ('BUDGET_CREATE', 'Budget Created'), ('BUDGET_DELETE', 'Budget Deleted')], max_length=30),
        ),
    ]
