# Generated by Django 5.2.17 on 2026-08-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_approval_status_alter_auditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password_encrypted', models.TextField(blank=True)),
                ('telegram_bot_token_encrypted', models.TextField(blank=True)),
                ('telegram_bot_username', models.CharField(blank=True, help_text='e.g. @DailyLedgerBot, shown to users so they know which bot to message', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_id',
            field=models.CharField(blank=True, help_text='Your numeric Telegram Chat ID (message @userinfobot to find it)', max_length=64),
        ),
        migrations.AddField(
            model_name='customuser',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('USER_REGISTER', 'User Registered'), ('USER_APPROVED', 'User Approved'), ('USER_REJECTED', 'User Rejected'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_REACTIVATED', 'User Reactivated'), ('PASSWORD_CHANGE', 'Password Changed'), ('PROFILE_UPDATE', 'Profile Updated'), ('SETTINGS_UPDATE', 'Settings Updated'), ('SETUP_COMPLETED', 'Setup Completed'), ('TRANSACTION_CREATE', 'Transaction Created'), ('TRANSACTION_UPDATE', 'Transaction Updated'), ('TRANSACTION_DELETE', 'Transaction Deleted'), ('BUDGET_CREATE', 'Budget Created'), ('BUDGET_DELETE', 'Budget Deleted')], max_length=30),
        ),
    ]
