# Generated by Django 5.2.17 on 2026-08-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_notificationsettings_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='from_display_name',
            field=models.CharField(blank=True, default='DailyLedger', max_length=100),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='reply_to_email',
            field=models.EmailField(blank=True, help_text='Defaults to the SMTP email above if left blank', max_length=254),
        ),
    ]
