# Generated by Django 6.1 on 2026-08-22 03:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_notificationsettings_from_display_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active_frequency', models.CharField(choices=[('NONE', 'Off'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly (Friday)'), ('MONTHLY', 'Monthly (1st)'), ('YEARLY', 'Yearly (Jan 1)')], default='NONE', max_length=10)),
                ('active_email_enabled', models.BooleanField(default=False)),
                ('active_telegram_enabled', models.BooleanField(default=False)),
                ('requested_frequency', models.CharField(choices=[('NONE', 'Off'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly (Friday)'), ('MONTHLY', 'Monthly (1st)'), ('YEARLY', 'Yearly (Jan 1)')], default='NONE', max_length=10)),
                ('requested_email_enabled', models.BooleanField(default=False)),
                ('requested_telegram_enabled', models.BooleanField(default=False)),
                ('review_status', models.CharField(choices=[('NONE', 'No request yet'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NONE', max_length=10)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('last_daily_sent_date', models.DateField(blank=True, null=True)),
                ('last_weekly_sent_date', models.DateField(blank=True, null=True)),
                ('last_monthly_sent_date', models.DateField(blank=True, null=True)),
                ('last_yearly_sent_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
