# Generated by Django 6.1 on 2026-08-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notificationpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='active_frequency',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='requested_frequency',
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='active_frequencies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='requested_frequencies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
