# Generated by Django 5.2.17 on 2026-08-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_notificationpreference_active_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('USER_REGISTER', 'User Registered'), ('USER_APPROVED', 'User Approved'), ('USER_REJECTED', 'User Rejected'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_REACTIVATED', 'User Reactivated'), ('PASSWORD_CHANGE', 'Password Changed'), ('PROFILE_UPDATE', 'Profile Updated'), ('SETTINGS_UPDATE', 'Settings Updated'), ('SETUP_COMPLETED', 'Setup Completed'), ('TRANSACTION_CREATE', 'Transaction Created'), ('TRANSACTION_UPDATE', 'Transaction Updated'), ('TRANSACTION_DELETE', 'Transaction Deleted'), ('BUDGET_CREATE', 'Budget Created'), ('BUDGET_DELETE', 'Budget Deleted'), ('EMAIL_SENT', 'Email Sent'), ('EMAIL_FAILED', 'Email Failed'), ('TELEGRAM_SENT', 'Telegram Sent'), ('TELEGRAM_FAILED', 'Telegram Failed'), ('BACKUP_SUCCESS', 'Backup Successful'), ('BACKUP_FAILED', 'Backup Failed')], max_length=30),
        ),
    ]
