# Generated by Django 5.2.17 on 2026-08-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_last_seen_customuser_session_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_password_reset_request_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='temp_password_expires_at',
            field=models.DateTimeField(blank=True, help_text='Set when a temporary password is issued via Forgot Password; cleared once the user sets a real password.', null=True),
        ),
    ]
